import type { PaginatedResponse } from "@/lib/api/operations"

export type HealthProductType = "VACCINE" | "ANTIBIOTIC" | "ANTIPARASITIC" | "ANTIFUNGAL" | "VITAMIN" | "MINERAL" | "ELECTROLYTE" | "DISINFECTANT" | "PROBIOTIC" | "OTHER"
export type VaccinationRoute = "DRINKING_WATER" | "EYE_DROP" | "SPRAY" | "INJECTION" | "FEED" | "WING_WEB" | "NASAL_DROP" | "OTHER"
export type VaccinationStatus = "SCHEDULED" | "DUE" | "COMPLETED" | "MISSED" | "CANCELLED"
export type IncidentSeverity = "LOW" | "MODERATE" | "HIGH" | "CRITICAL"
export type IncidentStatus = "OPEN" | "UNDER_TREATMENT" | "MONITORING" | "RESOLVED" | "CLOSED"
export type TreatmentStatus = "PLANNED" | "ACTIVE" | "COMPLETED" | "CANCELLED"

export interface HealthSummary { as_of_date:string; scheduled_vaccinations:number; due_vaccinations:number; missed_vaccinations:number; completed_vaccinations:number; open_incidents:number; incidents_under_treatment:number; critical_incidents:number; active_treatments:number; planned_treatments:number; active_egg_withdrawals:number; active_meat_withdrawals:number }
export interface HealthProduct { id:string; product_code:string; name:string; product_type:HealthProductType; manufacturer:string|null; active_ingredient:string|null; description:string|null; default_egg_withdrawal_days:number; default_meat_withdrawal_days:number; is_active:boolean; is_vaccine:boolean; created_at:string; updated_at:string }
export type HealthProductListResponse = PaginatedResponse<HealthProduct>
export interface VaccinationSchedule { id:string; flock_id:string; flock_code:string; flock_name:string; house_id:string; house_code:string; house_name:string; product_id:string|null; product_code:string|null; vaccine_name:string; disease_target:string|null; scheduled_date:string; reminder_date:string|null; target_age_days:number|null; planned_dose:string|null; route:VaccinationRoute; status:VaccinationStatus; days_until_due:number; reminder_active:boolean; is_overdue:boolean; notes:string|null; cancellation_reason:string|null; administration: { administration_date:string; birds_vaccinated:number; dose:string|null; route:VaccinationRoute; batch_number:string|null; veterinarian_name:string|null } | null; created_at:string; updated_at:string }
export type VaccinationScheduleListResponse = PaginatedResponse<VaccinationSchedule>
export interface HealthIncident { id:string; flock_id:string; flock_code:string; flock_name:string; house_id:string; house_code:string; incident_code:string; incident_date:string; severity:IncidentSeverity; status:IncidentStatus; affected_birds:number; symptoms:string; suspected_cause:string|null; diagnosis:string|null; veterinarian_name:string|null; isolation_required:boolean; isolation_details:string|null; notes:string|null; resolution_date:string|null; resolution_notes:string|null; is_resolved:boolean; treatment_count:number; created_at:string; updated_at:string }
export type HealthIncidentListResponse = PaginatedResponse<HealthIncident>
export interface TreatmentRecord { id:string; flock_id:string; flock_code:string; flock_name:string; health_incident_id:string|null; incident_code:string|null; product_id:string|null; product_code:string|null; product_name:string; treatment_date:string; end_date:string|null; birds_treated:number; dose:string|null; route:VaccinationRoute; purpose:string|null; prescribed_by:string|null; treatment_cost:string; egg_withdrawal_days:number; meat_withdrawal_days:number; egg_withdrawal_until:string|null; meat_withdrawal_until:string|null; is_egg_withdrawal_active:boolean; is_meat_withdrawal_active:boolean; status:TreatmentStatus; notes:string|null; is_completed:boolean; created_at:string; updated_at:string }
export type TreatmentRecordListResponse = PaginatedResponse<TreatmentRecord>

export type BirdLossType = "MORTALITY" | "CULLING"
export type BirdLossReason = "DISEASE" | "INJURY" | "PREDATION" | "HEAT_STRESS" | "COLD_STRESS" | "SUFFOCATION" | "STARVATION" | "DEHYDRATION" | "POISONING" | "LOW_PRODUCTION" | "DEFORMITY" | "OLD_AGE" | "AGGRESSION" | "VETERINARY_RECOMMENDATION" | "UNKNOWN" | "OTHER"
export type BirdDisposalMethod = "BURIAL" | "INCINERATION" | "COMPOSTING" | "RENDERING" | "VETERINARY_DISPOSAL" | "SOLD_FOR_SLAUGHTER" | "HOME_CONSUMPTION" | "OTHER" | "NOT_RECORDED"
export interface BirdLoss { id:string; flock_id:string; flock_code:string; flock_name:string; house_id:string; house_code:string; house_name:string; loss_date:string; loss_type:BirdLossType; quantity:number; reason_category:BirdLossReason; cause_details:string|null; disposal_method:BirdDisposalMethod; disposal_details:string|null; location:string|null; reference:string|null; notes:string|null; population_before:number; population_after:number; current_population:number; loss_percentage:string; daily_mortality_quantity:number; daily_mortality_percentage:string; mortality_threshold_percentage:string; mortality_alert:boolean; status:"ACTIVE"|"REVERSED"; is_reversed:boolean; reversal_reason:string|null; reversed_at:string|null; created_at:string; updated_at:string }
export type BirdLossListResponse = PaginatedResponse<BirdLoss>
export interface BirdLossSummary { date_from:string; date_to:string; flock_id:string|null; active_record_count:number; reversed_record_count:number; mortality_quantity:number; culling_quantity:number; total_loss_quantity:number; average_incident_loss_percentage:string; maximum_incident_loss_percentage:string; mortality_threshold_percentage:string; high_mortality_incidents:number; current_flock_population:number|null }
