from enum import StrEnum


class NotificationDeliveryStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AlertEventType(StrEnum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    REOPENED = "REOPENED"
    AUTO_RESOLVED = "AUTO_RESOLVED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    MANUALLY_REOPENED = "MANUALLY_REOPENED"
    ASSIGNED = "ASSIGNED"
    UNASSIGNED = "UNASSIGNED"
    MARKED_READ = "MARKED_READ"
    MARKED_UNREAD = "MARKED_UNREAD"
    DISMISSED = "DISMISSED"
    RESTORED = "RESTORED"
    DELIVERY_QUEUED = "DELIVERY_QUEUED"
    DELIVERY_SENT = "DELIVERY_SENT"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    DELIVERY_RETRIED = "DELIVERY_RETRIED"
