from enum import StrEnum


class AlertSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertType(StrEnum):
    LOW_FEED_STOCK = "LOW_FEED_STOCK"
    OVERDUE_VACCINATION = "OVERDUE_VACCINATION"
    HEALTH_INCIDENT = "HEALTH_INCIDENT"
    HIGH_MORTALITY = "HIGH_MORTALITY"
    OVERDUE_SUPPLIER_BILL = "OVERDUE_SUPPLIER_BILL"
    CUSTOMER_CREDIT_LIMIT = "CUSTOMER_CREDIT_LIMIT"
    NEGATIVE_CASH_BALANCE = "NEGATIVE_CASH_BALANCE"


class TrendMetric(StrEnum):
    EGG_PRODUCTION = "EGG_PRODUCTION"
    SALES_REVENUE = "SALES_REVENUE"
    OPERATING_EXPENSES = "OPERATING_EXPENSES"
    FEED_USAGE = "FEED_USAGE"
    BIRD_LOSSES = "BIRD_LOSSES"
