"use client"

import { useEffect, useMemo, useState } from "react"
import { Activity, CheckCircle2, HeartPulse, Plus, RefreshCcw, ShieldAlert, Stethoscope, Syringe, XCircle } from "lucide-react"
import { toast } from "sonner"

import { useAuth } from "@/components/auth/auth-provider"
import { EmptyState } from "@/components/operational/empty-state"
import { FormField, NativeSelect, Textarea } from "@/components/operational/form-controls"
import { PageHeading } from "@/components/operational/page-heading"
import { StatCard } from "@/components/operational/stat-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { browserApiRequest } from "@/lib/api/browser"
import type { Flock, FlockListResponse } from "@/lib/api/operations"
import type { HealthIncident, HealthIncidentListResponse, HealthProduct, HealthProductListResponse, HealthProductType, HealthSummary, IncidentSeverity, TreatmentRecord, TreatmentRecordListResponse, VaccinationRoute, VaccinationSchedule, VaccinationScheduleListResponse } from "@/lib/api/stage21c"
import { formatDate, formatEnum, formatNumber, todayIso } from "@/lib/operational/format"

type Tab = "incidents" | "vaccinations" | "treatments" | "products"
type DialogKind = Tab | null
const routes: VaccinationRoute[] = ["DRINKING_WATER","EYE_DROP","SPRAY","INJECTION","FEED","WING_WEB","NASAL_DROP","OTHER"]
const productTypes: HealthProductType[] = ["VACCINE","ANTIBIOTIC","ANTIPARASITIC","ANTIFUNGAL","VITAMIN","MINERAL","ELECTROLYTE","DISINFECTANT","PROBIOTIC","OTHER"]
const severities: IncidentSeverity[] = ["LOW","MODERATE","HIGH","CRITICAL"]

type IncidentFormData = { flock_id:string; incident_code:string; incident_date:string; severity:IncidentSeverity; affected_birds:string; symptoms:string; suspected_cause:string; veterinarian_name:string; isolation_required:boolean; isolation_details:string; notes:string }
type VaccinationFormData = { flock_id:string; product_id:string; vaccine_name:string; disease_target:string; scheduled_date:string; reminder_date:string; planned_dose:string; route:VaccinationRoute; notes:string }
type TreatmentFormData = { flock_id:string; health_incident_id:string; product_id:string; product_name:string; treatment_date:string; end_date:string; birds_treated:string; dose:string; route:VaccinationRoute; purpose:string; prescribed_by:string; treatment_cost:string; egg_withdrawal_days:string; meat_withdrawal_days:string; notes:string }
type ProductFormData = { product_code:string; name:string; product_type:HealthProductType; manufacturer:string; active_ingredient:string; description:string; default_egg_withdrawal_days:string; default_meat_withdrawal_days:string }

const emptySummary: HealthSummary = { as_of_date:todayIso(), scheduled_vaccinations:0, due_vaccinations:0, missed_vaccinations:0, completed_vaccinations:0, open_incidents:0, incidents_under_treatment:0, critical_incidents:0, active_treatments:0, planned_treatments:0, active_egg_withdrawals:0, active_meat_withdrawals:0 }

export function HealthWorkspace({ initialTab="incidents", initiallyCreateIncident=false }: { initialTab?:Tab; initiallyCreateIncident?:boolean }) {
  const { session } = useAuth()
  const [tab,setTab]=useState<Tab>(initialTab)
  const [summary,setSummary]=useState<HealthSummary>(emptySummary)
  const [flocks,setFlocks]=useState<Flock[]>([])
  const [products,setProducts]=useState<HealthProduct[]>([])
  const [incidents,setIncidents]=useState<HealthIncident[]>([])
  const [vaccinations,setVaccinations]=useState<VaccinationSchedule[]>([])
  const [treatments,setTreatments]=useState<TreatmentRecord[]>([])
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState<string|null>(null)
  const [reload,setReload]=useState(0)
  const [dialog,setDialog]=useState<DialogKind>(initiallyCreateIncident?"incidents":null)
  const permissions=session.permissions
  const canProducts=permissions.includes("health.products.manage")
  const canVaccinations=permissions.includes("health.vaccinations.schedule")
  const canCompleteVaccinations=permissions.includes("health.vaccinations.complete")
  const canIncidents=permissions.includes("health.incidents.manage")
  const canResolve=permissions.includes("health.resolve")
  const canTreatments=permissions.includes("health.treatments.manage")

  const [incidentForm,setIncidentForm]=useState<IncidentFormData>({ flock_id:"", incident_code:"", incident_date:todayIso(), severity:"MODERATE", affected_birds:"1", symptoms:"", suspected_cause:"", veterinarian_name:"", isolation_required:false, isolation_details:"", notes:"" })
  const [vaccinationForm,setVaccinationForm]=useState<VaccinationFormData>({ flock_id:"", product_id:"", vaccine_name:"", disease_target:"", scheduled_date:todayIso(), reminder_date:"", planned_dose:"", route:"DRINKING_WATER", notes:"" })
  const [treatmentForm,setTreatmentForm]=useState<TreatmentFormData>({ flock_id:"", health_incident_id:"", product_id:"", product_name:"", treatment_date:todayIso(), end_date:"", birds_treated:"1", dose:"", route:"DRINKING_WATER", purpose:"", prescribed_by:"", treatment_cost:"0", egg_withdrawal_days:"0", meat_withdrawal_days:"0", notes:"" })
  const [productForm,setProductForm]=useState<ProductFormData>({ product_code:"", name:"", product_type:"VACCINE", manufacturer:"", active_ingredient:"", description:"", default_egg_withdrawal_days:"0", default_meat_withdrawal_days:"0" })
  const [saving,setSaving]=useState(false)

  useEffect(()=>{ const controller=new AbortController(); async function load(){ setLoading(true); setError(null); try{ const [s,f,p,i,v,t]=await Promise.all([
    browserApiRequest<HealthSummary>("/health/summary",{signal:controller.signal}),
    browserApiRequest<FlockListResponse>("/flocks?limit=100&status=ACTIVE",{signal:controller.signal}),
    browserApiRequest<HealthProductListResponse>("/health/products?limit=100",{signal:controller.signal}),
    browserApiRequest<HealthIncidentListResponse>("/health/incidents?limit=100",{signal:controller.signal}),
    browserApiRequest<VaccinationScheduleListResponse>("/health/vaccinations?limit=100",{signal:controller.signal}),
    browserApiRequest<TreatmentRecordListResponse>("/health/treatments?limit=100",{signal:controller.signal}),
  ]); if(!controller.signal.aborted){ setSummary(s); setFlocks(f.items); setProducts(p.items); setIncidents(i.items); setVaccinations(v.items); setTreatments(t.items) } } catch(caught){ if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:"Health records could not be loaded.") } finally{ if(!controller.signal.aborted)setLoading(false) } } void load(); return()=>controller.abort() },[reload])

  const openCount=useMemo(()=>incidents.filter((i)=>!i.is_resolved).length,[incidents])
  async function createIncident(){ if(!incidentForm.flock_id||incidentForm.incident_code.trim().length<2||incidentForm.symptoms.trim().length<3)return toast.error("Select a flock and enter the incident code and symptoms."); setSaving(true); try{ await browserApiRequest("/health/incidents",{method:"POST",body:JSON.stringify({...incidentForm,affected_birds:Number(incidentForm.affected_birds),suspected_cause:incidentForm.suspected_cause||null,veterinarian_name:incidentForm.veterinarian_name||null,isolation_details:incidentForm.isolation_details||null,notes:incidentForm.notes||null})}); setDialog(null); setReload(v=>v+1); toast.success("Health incident recorded.") }catch(c){toast.error(c instanceof Error?c.message:"Incident could not be created.")}finally{setSaving(false)} }
  async function createVaccination(){ if(!vaccinationForm.flock_id||vaccinationForm.vaccine_name.trim().length<2)return toast.error("Select a flock and enter a vaccine name."); setSaving(true); try{ await browserApiRequest("/health/vaccinations",{method:"POST",body:JSON.stringify({...vaccinationForm,product_id:vaccinationForm.product_id||null,disease_target:vaccinationForm.disease_target||null,reminder_date:vaccinationForm.reminder_date||null,planned_dose:vaccinationForm.planned_dose||null,notes:vaccinationForm.notes||null})}); setDialog(null); setReload(v=>v+1); toast.success("Vaccination scheduled.") }catch(c){toast.error(c instanceof Error?c.message:"Vaccination could not be scheduled.")}finally{setSaving(false)} }
  async function createTreatment(){ if(!treatmentForm.flock_id||Number(treatmentForm.birds_treated)<1)return toast.error("Select a flock and enter birds treated."); setSaving(true); try{ await browserApiRequest("/health/treatments",{method:"POST",body:JSON.stringify({...treatmentForm,health_incident_id:treatmentForm.health_incident_id||null,product_id:treatmentForm.product_id||null,product_name:treatmentForm.product_name||null,end_date:treatmentForm.end_date||null,birds_treated:Number(treatmentForm.birds_treated),dose:treatmentForm.dose||null,purpose:treatmentForm.purpose||null,prescribed_by:treatmentForm.prescribed_by||null,treatment_cost:treatmentForm.treatment_cost,egg_withdrawal_days:Number(treatmentForm.egg_withdrawal_days),meat_withdrawal_days:Number(treatmentForm.meat_withdrawal_days),notes:treatmentForm.notes||null})}); setDialog(null); setReload(v=>v+1); toast.success("Treatment recorded.") }catch(c){toast.error(c instanceof Error?c.message:"Treatment could not be recorded.")}finally{setSaving(false)} }
  async function createProduct(){ if(productForm.product_code.trim().length<2||productForm.name.trim().length<2)return toast.error("Enter a product code and name."); setSaving(true); try{ await browserApiRequest("/health/products",{method:"POST",body:JSON.stringify({...productForm,manufacturer:productForm.manufacturer||null,active_ingredient:productForm.active_ingredient||null,description:productForm.description||null,default_egg_withdrawal_days:Number(productForm.default_egg_withdrawal_days),default_meat_withdrawal_days:Number(productForm.default_meat_withdrawal_days)})}); setDialog(null); setReload(v=>v+1); toast.success("Health product registered.") }catch(c){toast.error(c instanceof Error?c.message:"Product could not be registered.")}finally{setSaving(false)} }
  async function simpleAction(path:string,body:Record<string,unknown>|undefined,message:string){ try{await browserApiRequest(path,{method:"POST",body:body?JSON.stringify(body):undefined}); setReload(v=>v+1); toast.success(message)}catch(c){toast.error(c instanceof Error?c.message:"Action failed.")} }

  if(loading)return <div className="space-y-5"><Skeleton className="h-20 rounded-2xl"/><div className="grid gap-4 md:grid-cols-4">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-32 rounded-2xl"/>)}</div><Skeleton className="h-96 rounded-3xl"/></div>
  if(error)return <EmptyState icon={XCircle} title="Health workspace unavailable" description={error} actionLabel="Try again" onAction={()=>setReload(v=>v+1)}/>

  const actionAllowed = tab==="incidents"?canIncidents:tab==="vaccinations"?canVaccinations:tab==="treatments"?canTreatments:canProducts
  return <div className="space-y-8">
    <PageHeading icon={Stethoscope} eyebrow="Flock wellbeing" title="Health management" description="Manage veterinary products, vaccination schedules, health incidents, treatments, and withdrawal periods." actions={<><Button variant="outline" className="rounded-xl" onClick={()=>setReload(v=>v+1)}><RefreshCcw className="size-4"/>Refresh</Button>{actionAllowed?<Button className="rounded-xl" onClick={()=>setDialog(tab)}><Plus className="size-4"/>Add {tab.slice(0,-1)}</Button>:null}</>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Open incidents" value={formatNumber(openCount)} helper={`${summary.critical_incidents} critical`} icon={ShieldAlert} tone={summary.critical_incidents?"danger":"primary"}/><StatCard label="Vaccinations due" value={formatNumber(summary.due_vaccinations)} helper={`${summary.missed_vaccinations} missed`} icon={Syringe} tone="warning"/><StatCard label="Active treatments" value={formatNumber(summary.active_treatments)} helper={`${summary.planned_treatments} planned`} icon={Activity} tone="info"/><StatCard label="Active withdrawals" value={formatNumber(summary.active_egg_withdrawals+summary.active_meat_withdrawals)} helper="Egg and meat restrictions" icon={HeartPulse}/></div>
    <div className="flex flex-wrap gap-2">{(["incidents","vaccinations","treatments","products"] as Tab[]).map(item=><Button key={item} variant={tab===item?"default":"outline"} className="rounded-xl" onClick={()=>setTab(item)}>{formatEnum(item)}</Button>)}</div>
    <Card className="overflow-hidden rounded-3xl border-border/75 bg-card/70">
      {tab==="incidents"?<RecordTable headers={["Incident / flock","Severity","Affected","Status","Action"]} empty={incidents.length===0} emptyText="No health incidents have been recorded.">{incidents.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.incident_code} · {item.flock_name}</p><p className="text-xs text-muted-foreground">{formatDate(item.incident_date)} · {item.house_code}</p></TableCell><TableCell><Badge variant="outline">{formatEnum(item.severity)}</Badge></TableCell><TableCell>{formatNumber(item.affected_birds)}</TableCell><TableCell><Badge variant="outline">{formatEnum(item.status)}</Badge></TableCell><TableCell>{canResolve&&!item.is_resolved?<Button size="sm" onClick={()=>{const notes=window.prompt("Resolution notes (minimum 5 characters)");if(notes&&notes.length>=5)void simpleAction(`/health/incidents/${item.id}/resolve`,{resolution_date:todayIso(),resolution_notes:notes},"Incident resolved.")}}><CheckCircle2 className="size-4"/>Resolve</Button>:"—"}</TableCell></TableRow>)}</RecordTable>:null}
      {tab==="vaccinations"?<RecordTable headers={["Vaccine / flock","Scheduled","Route","Status","Action"]} empty={vaccinations.length===0} emptyText="No vaccination schedules are available.">{vaccinations.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.vaccine_name}</p><p className="text-xs text-muted-foreground">{item.flock_code} · {item.disease_target||"General prevention"}</p></TableCell><TableCell>{formatDate(item.scheduled_date)}</TableCell><TableCell>{formatEnum(item.route)}</TableCell><TableCell><Badge variant="outline">{formatEnum(item.status)}</Badge></TableCell><TableCell><div className="flex gap-2">{canCompleteVaccinations&&["SCHEDULED","DUE","MISSED"].includes(item.status)?<Button size="sm" onClick={()=>{const birds=window.prompt("Birds vaccinated",String(flocks.find(f=>f.id===item.flock_id)?.current_population||1));if(birds)void simpleAction(`/health/vaccinations/${item.id}/complete`,{administration_date:todayIso(),birds_vaccinated:Number(birds),product_id:item.product_id,dose:item.planned_dose,route:item.route,batch_number:null,expiry_date:null,administered_by_name:session.user.full_name,veterinarian_name:null,notes:null},"Vaccination completed.")}}><CheckCircle2 className="size-4"/>Complete</Button>:null}{canVaccinations&&["SCHEDULED","DUE","MISSED"].includes(item.status)?<Button size="sm" variant="outline" onClick={()=>{const reason=window.prompt("Cancellation reason");if(reason&&reason.length>=5)void simpleAction(`/health/vaccinations/${item.id}/cancel`,{reason},"Vaccination cancelled.")}}>Cancel</Button>:null}</div></TableCell></TableRow>)}</RecordTable>:null}
      {tab==="treatments"?<RecordTable headers={["Treatment / flock","Date","Birds","Withdrawal","Action"]} empty={treatments.length===0} emptyText="No treatment records are available.">{treatments.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.product_name}</p><p className="text-xs text-muted-foreground">{item.flock_code} · {item.purpose||"Treatment"}</p></TableCell><TableCell>{formatDate(item.treatment_date)}<p className="text-xs text-muted-foreground">{formatEnum(item.status)}</p></TableCell><TableCell>{formatNumber(item.birds_treated)}</TableCell><TableCell>{item.is_egg_withdrawal_active||item.is_meat_withdrawal_active?<Badge variant="destructive">Active</Badge>:"None"}</TableCell><TableCell>{canResolve&&["PLANNED","ACTIVE"].includes(item.status)?<Button size="sm" onClick={()=>void simpleAction(`/health/treatments/${item.id}/complete`,{end_date:todayIso(),notes:"Treatment course completed."},"Treatment completed.")}><CheckCircle2 className="size-4"/>Complete</Button>:"—"}</TableCell></TableRow>)}</RecordTable>:null}
      {tab==="products"?<RecordTable headers={["Product","Type","Withdrawal","Status","Action"]} empty={products.length===0} emptyText="No health products are registered.">{products.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.product_code} · {item.name}</p><p className="text-xs text-muted-foreground">{item.manufacturer||"Manufacturer not recorded"}</p></TableCell><TableCell>{formatEnum(item.product_type)}</TableCell><TableCell>{item.default_egg_withdrawal_days}d egg / {item.default_meat_withdrawal_days}d meat</TableCell><TableCell><Badge variant="outline">{item.is_active?"Active":"Inactive"}</Badge></TableCell><TableCell>{canProducts?<Button size="sm" variant="outline" onClick={()=>void simpleAction(`/health/products/${item.id}/${item.is_active?"deactivate":"activate"}`,undefined,item.is_active?"Product deactivated.":"Product activated.")}>{item.is_active?"Deactivate":"Activate"}</Button>:"—"}</TableCell></TableRow>)}</RecordTable>:null}
    </Card>
    <Dialog open={dialog!==null} onOpenChange={open=>!open&&setDialog(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Add {dialog?formatEnum(dialog.slice(0,-1)):"record"}</DialogTitle><DialogDescription>Required values are validated by the PoultryPulse API.</DialogDescription></DialogHeader>{dialog==="incidents"?<IncidentForm value={incidentForm} setValue={setIncidentForm} flocks={flocks}/>:dialog==="vaccinations"?<VaccinationForm value={vaccinationForm} setValue={setVaccinationForm} flocks={flocks} products={products}/>:dialog==="treatments"?<TreatmentForm value={treatmentForm} setValue={setTreatmentForm} flocks={flocks} incidents={incidents} products={products}/>:dialog==="products"?<ProductForm value={productForm} setValue={setProductForm}/>:null}<DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>Cancel</Button><Button disabled={saving} onClick={()=>void (dialog==="incidents"?createIncident():dialog==="vaccinations"?createVaccination():dialog==="treatments"?createTreatment():createProduct())}>{saving?"Saving…":"Save record"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}

function RecordTable({headers,children,empty,emptyText}:{headers:string[];children:React.ReactNode;empty:boolean;emptyText:string}){return empty?<div className="p-5"><EmptyState icon={Stethoscope} title="Nothing recorded" description={emptyText}/></div>:<div className="overflow-x-auto"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></div>}
function IncidentForm({value,setValue,flocks}:{value:IncidentFormData;setValue:(v:IncidentFormData)=>void;flocks:Flock[]}){return <div className="grid gap-4 sm:grid-cols-2"><SelectFlock value={value.flock_id} onChange={v=>setValue({...value,flock_id:v})} flocks={flocks}/><FormField label="Incident code" htmlFor="incident-code" required><Input id="incident-code" value={value.incident_code} onChange={e=>setValue({...value,incident_code:e.target.value})}/></FormField><FormField label="Incident date" htmlFor="incident-date"><Input id="incident-date" type="date" value={value.incident_date} onChange={e=>setValue({...value,incident_date:e.target.value})}/></FormField><FormField label="Severity" htmlFor="incident-severity"><NativeSelect id="incident-severity" value={value.severity} onChange={e=>setValue({...value,severity:e.target.value as IncidentSeverity})}>{severities.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField label="Affected birds" htmlFor="affected" required><Input id="affected" type="number" min="1" value={value.affected_birds} onChange={e=>setValue({...value,affected_birds:e.target.value})}/></FormField><FormField label="Veterinarian" htmlFor="vet"><Input id="vet" value={value.veterinarian_name} onChange={e=>setValue({...value,veterinarian_name:e.target.value})}/></FormField><FormField className="sm:col-span-2" label="Symptoms" htmlFor="symptoms" required><Textarea id="symptoms" value={value.symptoms} onChange={e=>setValue({...value,symptoms:e.target.value})}/></FormField><FormField className="sm:col-span-2" label="Suspected cause" htmlFor="cause"><Input id="cause" value={value.suspected_cause} onChange={e=>setValue({...value,suspected_cause:e.target.value})}/></FormField></div>}
function VaccinationForm({value,setValue,flocks,products}:{value:VaccinationFormData;setValue:(v:VaccinationFormData)=>void;flocks:Flock[];products:HealthProduct[]}){return <div className="grid gap-4 sm:grid-cols-2"><SelectFlock value={value.flock_id} onChange={v=>setValue({...value,flock_id:v})} flocks={flocks}/><FormField label="Health product" htmlFor="v-product"><NativeSelect id="v-product" value={value.product_id} onChange={e=>{const p=products.find(x=>x.id===e.target.value);setValue({...value,product_id:e.target.value,vaccine_name:p?.name||value.vaccine_name})}}><option value="">No linked product</option>{products.filter(p=>p.is_vaccine&&p.is_active).map(p=><option key={p.id} value={p.id}>{p.product_code} · {p.name}</option>)}</NativeSelect></FormField><FormField label="Vaccine name" htmlFor="v-name" required><Input id="v-name" value={value.vaccine_name} onChange={e=>setValue({...value,vaccine_name:e.target.value})}/></FormField><FormField label="Disease target" htmlFor="v-target"><Input id="v-target" value={value.disease_target} onChange={e=>setValue({...value,disease_target:e.target.value})}/></FormField><FormField label="Scheduled date" htmlFor="v-date"><Input id="v-date" type="date" value={value.scheduled_date} onChange={e=>setValue({...value,scheduled_date:e.target.value})}/></FormField><FormField label="Reminder date" htmlFor="v-reminder"><Input id="v-reminder" type="date" value={value.reminder_date} onChange={e=>setValue({...value,reminder_date:e.target.value})}/></FormField><FormField label="Route" htmlFor="v-route"><NativeSelect id="v-route" value={value.route} onChange={e=>setValue({...value,route:e.target.value as VaccinationRoute})}>{routes.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField label="Planned dose" htmlFor="v-dose"><Input id="v-dose" value={value.planned_dose} onChange={e=>setValue({...value,planned_dose:e.target.value})}/></FormField></div>}
function TreatmentForm({value,setValue,flocks,incidents,products}:{value:TreatmentFormData;setValue:(v:TreatmentFormData)=>void;flocks:Flock[];incidents:HealthIncident[];products:HealthProduct[]}){return <div className="grid gap-4 sm:grid-cols-2"><SelectFlock value={value.flock_id} onChange={v=>setValue({...value,flock_id:v})} flocks={flocks}/><FormField label="Linked incident" htmlFor="t-incident"><NativeSelect id="t-incident" value={value.health_incident_id} onChange={e=>setValue({...value,health_incident_id:e.target.value})}><option value="">None</option>{incidents.filter(i=>!i.is_resolved).map(i=><option key={i.id} value={i.id}>{i.incident_code} · {i.flock_code}</option>)}</NativeSelect></FormField><FormField label="Health product" htmlFor="t-product"><NativeSelect id="t-product" value={value.product_id} onChange={e=>{const p=products.find(x=>x.id===e.target.value);setValue({...value,product_id:e.target.value,product_name:p?.name||"",egg_withdrawal_days:String(p?.default_egg_withdrawal_days||0),meat_withdrawal_days:String(p?.default_meat_withdrawal_days||0)})}}><option value="">Manual product name</option>{products.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.product_code} · {p.name}</option>)}</NativeSelect></FormField><FormField label="Product name" htmlFor="t-name"><Input id="t-name" disabled={Boolean(value.product_id)} value={value.product_name} onChange={e=>setValue({...value,product_name:e.target.value})}/></FormField><FormField label="Treatment date" htmlFor="t-date"><Input id="t-date" type="date" value={value.treatment_date} onChange={e=>setValue({...value,treatment_date:e.target.value})}/></FormField><FormField label="Birds treated" htmlFor="t-birds" required><Input id="t-birds" type="number" min="1" value={value.birds_treated} onChange={e=>setValue({...value,birds_treated:e.target.value})}/></FormField><FormField label="Route" htmlFor="t-route"><NativeSelect id="t-route" value={value.route} onChange={e=>setValue({...value,route:e.target.value as VaccinationRoute})}>{routes.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField label="Treatment cost" htmlFor="t-cost"><Input id="t-cost" type="number" min="0" value={value.treatment_cost} onChange={e=>setValue({...value,treatment_cost:e.target.value})}/></FormField><FormField label="Egg withdrawal days" htmlFor="t-egg"><Input id="t-egg" type="number" min="0" value={value.egg_withdrawal_days} onChange={e=>setValue({...value,egg_withdrawal_days:e.target.value})}/></FormField><FormField label="Meat withdrawal days" htmlFor="t-meat"><Input id="t-meat" type="number" min="0" value={value.meat_withdrawal_days} onChange={e=>setValue({...value,meat_withdrawal_days:e.target.value})}/></FormField><FormField className="sm:col-span-2" label="Purpose" htmlFor="t-purpose"><Input id="t-purpose" value={value.purpose} onChange={e=>setValue({...value,purpose:e.target.value})}/></FormField></div>}
function ProductForm({value,setValue}:{value:ProductFormData;setValue:(v:ProductFormData)=>void}){return <div className="grid gap-4 sm:grid-cols-2"><FormField label="Product code" htmlFor="p-code" required><Input id="p-code" value={value.product_code} onChange={e=>setValue({...value,product_code:e.target.value})}/></FormField><FormField label="Name" htmlFor="p-name" required><Input id="p-name" value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></FormField><FormField label="Type" htmlFor="p-type"><NativeSelect id="p-type" value={value.product_type} onChange={e=>setValue({...value,product_type:e.target.value as HealthProductType})}>{productTypes.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField label="Manufacturer" htmlFor="p-maker"><Input id="p-maker" value={value.manufacturer} onChange={e=>setValue({...value,manufacturer:e.target.value})}/></FormField><FormField label="Active ingredient" htmlFor="p-active"><Input id="p-active" value={value.active_ingredient} onChange={e=>setValue({...value,active_ingredient:e.target.value})}/></FormField><FormField label="Egg withdrawal days" htmlFor="p-egg"><Input id="p-egg" type="number" min="0" value={value.default_egg_withdrawal_days} onChange={e=>setValue({...value,default_egg_withdrawal_days:e.target.value})}/></FormField><FormField label="Meat withdrawal days" htmlFor="p-meat"><Input id="p-meat" type="number" min="0" value={value.default_meat_withdrawal_days} onChange={e=>setValue({...value,default_meat_withdrawal_days:e.target.value})}/></FormField><FormField className="sm:col-span-2" label="Description" htmlFor="p-desc"><Textarea id="p-desc" value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></FormField></div>}
function SelectFlock({value,onChange,flocks}:{value:string;onChange:(v:string)=>void;flocks:Flock[]}){return <FormField label="Flock" htmlFor="health-flock" required><NativeSelect id="health-flock" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select flock</option>{flocks.map(f=><option key={f.id} value={f.id}>{f.flock_code} · {f.name}</option>)}</NativeSelect></FormField>}
