"use client"

import { useEffect, useMemo, useState } from "react"
import { CalendarDays, CheckCircle2, ClipboardList, Egg, Eye, Pencil, Plus, RefreshCcw, Search, Send, XCircle } from "lucide-react"
import { toast } from "sonner"

import { useAuth } from "@/components/auth/auth-provider"
import { EmptyState } from "@/components/operational/empty-state"
import { FormField, NativeSelect, Textarea } from "@/components/operational/form-controls"
import { PageHeading } from "@/components/operational/page-heading"
import { PaginationControls } from "@/components/operational/pagination-controls"
import { StatCard } from "@/components/operational/stat-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { browserApiRequest } from "@/lib/api/browser"
import type { Flock, FlockListResponse } from "@/lib/api/operations"
import type { ProductionListResponse, ProductionRecord, ProductionStatus, ProductionSummary } from "@/lib/api/stage21b"
import { formatDate, formatEnum, formatNumber, todayIso } from "@/lib/operational/format"

const LIMIT = 20
const statuses: ProductionStatus[] = ["DRAFT", "SUBMITTED", "CONFIRMED", "REJECTED", "VOIDED"]
const emptySummary: ProductionSummary = { date_from: todayIso(), date_to: todayIso(), status: null, record_count: 0, bird_days: 0, morning_eggs: 0, afternoon_eggs: 0, evening_eggs: 0, total_collected: 0, large_eggs: 0, medium_eggs: 0, small_eggs: 0, damaged_eggs: 0, rejected_eggs: 0, saleable_eggs: 0, weighted_laying_percentage: "0" }

type FormData = { flock_id: string; production_date: string; morning_eggs: string; afternoon_eggs: string; evening_eggs: string; large_eggs: string; medium_eggs: string; small_eggs: string; damaged_eggs: string; rejected_eggs: string; notes: string }
const blankForm = (): FormData => ({ flock_id: "", production_date: todayIso(), morning_eggs: "0", afternoon_eggs: "0", evening_eggs: "0", large_eggs: "0", medium_eggs: "0", small_eggs: "0", damaged_eggs: "0", rejected_eggs: "0", notes: "" })

export function ProductionWorkspace({ initiallyCreate = false }: { initiallyCreate?: boolean }) {
  const { session } = useAuth()
  const [records, setRecords] = useState<ProductionRecord[]>([])
  const [flocks, setFlocks] = useState<Flock[]>([])
  const [summary, setSummary] = useState<ProductionSummary>(emptySummary)
  const [offset, setOffset] = useState(0); const [total, setTotal] = useState(0)
  const [status, setStatus] = useState<ProductionStatus | "">(""); const [search, setSearch] = useState("")
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const [reload, setReload] = useState(0); const [selected, setSelected] = useState<ProductionRecord | null>(null)
  const [formOpen, setFormOpen] = useState(initiallyCreate); const [editing, setEditing] = useState<ProductionRecord | null>(null)
  const [form, setForm] = useState<FormData>(blankForm); const [saving, setSaving] = useState(false)
  const [rejectOpen, setRejectOpen] = useState(false); const [rejectReason, setRejectReason] = useState("")
  const canCreate = session.permissions.includes("production.create")
  const canEdit = session.permissions.includes("production.adjust")
  const canSubmit = session.permissions.includes("production.submit")
  const canConfirm = session.permissions.includes("production.confirm")

  useEffect(() => { void browserApiRequest<FlockListResponse>("/flocks?limit=100&status=ACTIVE").then((p) => setFlocks(p.items)).catch(() => setFlocks([])) }, [])
  const query = useMemo(() => { const p = new URLSearchParams({ offset: String(offset), limit: String(LIMIT) }); if (status) p.set("status", status); if (search.trim()) p.set("search", search.trim()); return p.toString() }, [offset, search, status])
  useEffect(() => { const controller = new AbortController(); async function load() { setLoading(true); try { const [list, totals] = await Promise.all([browserApiRequest<ProductionListResponse>(`/production-records?${query}`, { signal: controller.signal }), browserApiRequest<ProductionSummary>("/production-records/summary", { signal: controller.signal })]); if (!controller.signal.aborted) { setRecords(list.items); setTotal(list.total); setSummary(totals); setError(null) } } catch (caught) { if (!controller.signal.aborted) setError(caught instanceof Error ? caught.message : "Production records could not be loaded.") } finally { if (!controller.signal.aborted) setLoading(false) } } void load(); return () => controller.abort() }, [query, reload])

  function openCreate() { setEditing(null); setForm(blankForm()); setFormOpen(true) }
  function openEdit(item: ProductionRecord) { setEditing(item); setForm({ flock_id: item.flock_id, production_date: item.production_date, morning_eggs: String(item.morning_eggs), afternoon_eggs: String(item.afternoon_eggs), evening_eggs: String(item.evening_eggs), large_eggs: String(item.large_eggs), medium_eggs: String(item.medium_eggs), small_eggs: String(item.small_eggs), damaged_eggs: String(item.damaged_eggs), rejected_eggs: String(item.rejected_eggs), notes: item.notes ?? "" }); setFormOpen(true) }
  async function save() { if (!form.flock_id) return toast.error("Select a flock."); setSaving(true); const payload = Object.fromEntries(Object.entries(form).map(([k,v]) => k.endsWith("eggs") ? [k, Number(v)] : [k, v || null])); try { const saved = await browserApiRequest<ProductionRecord>(editing ? `/production-records/${editing.id}` : "/production-records", { method: editing ? "PATCH" : "POST", body: JSON.stringify(editing ? { ...payload, flock_id: undefined, production_date: undefined } : payload) }); toast.success(editing ? "Production record updated." : "Production draft created."); setFormOpen(false); setSelected(saved); setReload((v) => v + 1) } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Production record could not be saved.") } finally { setSaving(false) } }
  async function action(name: "submit" | "confirm") { if (!selected) return; try { const saved = await browserApiRequest<ProductionRecord>(`/production-records/${selected.id}/${name}`, { method: "POST" }); setSelected(saved); setReload((v) => v + 1); toast.success(`Production record ${name === "submit" ? "submitted" : "confirmed"}.`) } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Action failed.") } }
  async function reject() { if (!selected || rejectReason.trim().length < 5) return toast.error("Enter a rejection reason of at least 5 characters."); try { const saved = await browserApiRequest<ProductionRecord>(`/production-records/${selected.id}/reject`, { method: "POST", body: JSON.stringify({ reason: rejectReason.trim() }) }); setSelected(saved); setRejectOpen(false); setRejectReason(""); setReload((v) => v + 1); toast.success("Production record rejected.") } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Record could not be rejected.") } }

  return <div className="space-y-8">
    <PageHeading icon={ClipboardList} eyebrow="Farm operations" title="Daily egg production" description="Capture collections, grade eggs, review laying performance, and move records through approval." actions={canCreate ? <Button className="rounded-xl" onClick={openCreate}><Plus className="size-4" />Record production</Button> : null} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Records" value={formatNumber(summary.record_count)} helper={`${formatDate(summary.date_from)} – ${formatDate(summary.date_to)}`} icon={CalendarDays} /><StatCard label="Eggs collected" value={formatNumber(summary.total_collected)} helper="Selected period" icon={Egg} /><StatCard label="Saleable eggs" value={formatNumber(summary.saleable_eggs)} helper="Confirmed grading output" icon={CheckCircle2} tone="info" /><StatCard label="Laying rate" value={`${Number(summary.weighted_laying_percentage).toFixed(1)}%`} helper="Weighted average" icon={RefreshCcw} tone="warning" /></div>
    <Card className="overflow-hidden rounded-3xl border-border/75 bg-card/70">
      <div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_220px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-10 rounded-xl pl-9" placeholder="Search flock or house…" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0) }} /></div><NativeSelect className="h-10 rounded-xl" value={status} onChange={(e) => { setStatus(e.target.value as ProductionStatus | ""); setOffset(0) }}><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{formatEnum(item)}</option>)}</NativeSelect><Button variant="outline" className="rounded-xl" onClick={() => setReload((v) => v + 1)}><RefreshCcw className="size-4" />Refresh</Button></div>
      {loading ? <div className="space-y-3 p-5">{Array.from({ length: 6 }).map((_,i) => <Skeleton key={i} className="h-16 rounded-xl" />)}</div> : error ? <div className="p-5"><EmptyState icon={XCircle} title="Production is unavailable" description={error} actionLabel="Try again" onAction={() => setReload((v) => v + 1)} /></div> : records.length === 0 ? <div className="p-5"><EmptyState icon={Egg} title="No production records" description="Create the first daily production draft or adjust the current filters." actionLabel={canCreate ? "Record production" : undefined} onAction={canCreate ? openCreate : undefined} /></div> : <><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead className="pl-5">Date / flock</TableHead><TableHead>Collected</TableHead><TableHead>Saleable</TableHead><TableHead>Laying</TableHead><TableHead>Status</TableHead><TableHead className="pr-5 text-right">Open</TableHead></TableRow></TableHeader><TableBody>{records.map((item) => <TableRow key={item.id}><TableCell className="pl-5"><p className="font-medium">{formatDate(item.production_date)}</p><p className="text-xs text-muted-foreground">{item.flock_code} · {item.house_code}</p></TableCell><TableCell className="font-mono">{formatNumber(item.total_collected)}</TableCell><TableCell className="font-mono">{formatNumber(item.saleable_eggs)}</TableCell><TableCell>{Number(item.laying_percentage).toFixed(1)}%</TableCell><TableCell><Badge variant="outline" className="rounded-full">{formatEnum(item.status)}</Badge></TableCell><TableCell className="pr-5 text-right"><Button size="icon-sm" variant="outline" onClick={() => setSelected(item)}><Eye className="size-4" /></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 p-4 md:hidden">{records.map((item) => <button type="button" key={item.id} onClick={() => setSelected(item)} className="rounded-2xl border p-4 text-left"><div className="flex justify-between"><div><p className="font-medium">{item.flock_name}</p><p className="text-xs text-muted-foreground">{formatDate(item.production_date)}</p></div><Badge variant="outline">{formatEnum(item.status)}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span>{formatNumber(item.total_collected)} eggs</span><span>{formatNumber(item.saleable_eggs)} saleable</span><span>{Number(item.laying_percentage).toFixed(1)}%</span></div></button>)}</div><PaginationControls offset={offset} limit={LIMIT} total={total} onOffsetChange={setOffset} /></>}
    </Card>
    <Dialog open={formOpen} onOpenChange={setFormOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{editing ? "Edit production draft" : "Record daily production"}</DialogTitle><DialogDescription>Collection totals must match or exceed the graded egg total.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><FormField label="Flock" htmlFor="production-flock" required><NativeSelect id="production-flock" disabled={Boolean(editing)} value={form.flock_id} onChange={(e) => setForm({ ...form, flock_id: e.target.value })}><option value="">Select flock</option>{flocks.map((item) => <option key={item.id} value={item.id}>{item.flock_code} · {item.name}</option>)}</NativeSelect></FormField><FormField label="Production date" htmlFor="production-date" required><Input id="production-date" type="date" disabled={Boolean(editing)} value={form.production_date} onChange={(e) => setForm({ ...form, production_date: e.target.value })} /></FormField>{(["morning_eggs","afternoon_eggs","evening_eggs","large_eggs","medium_eggs","small_eggs","damaged_eggs","rejected_eggs"] as const).map((key) => <FormField key={key} label={formatEnum(key)} htmlFor={key}><Input id={key} type="number" min="0" value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></FormField>)}<FormField className="sm:col-span-2" label="Notes" htmlFor="production-notes"><Textarea id="production-notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></FormField></div><DialogFooter><Button variant="outline" onClick={() => setFormOpen(false)}>Cancel</Button><Button disabled={saving} onClick={() => void save()}>{saving ? "Saving…" : editing ? "Save changes" : "Create draft"}</Button></DialogFooter></DialogContent></Dialog>
    <Sheet open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{selected?.flock_name ?? "Production record"}</SheetTitle><SheetDescription>{selected ? `${formatDate(selected.production_date)} · ${selected.house_code}` : ""}</SheetDescription></SheetHeader>{selected ? <div className="space-y-5 p-4"><div className="grid grid-cols-2 gap-3">{[["Collected", selected.total_collected],["Saleable", selected.saleable_eggs],["Birds present", selected.birds_present],["Laying %", `${Number(selected.laying_percentage).toFixed(1)}%`]].map(([label,value]) => <Card key={String(label)} className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-mono text-xl font-semibold">{typeof value === "number" ? formatNumber(value) : value}</p></Card>)}</div><div className="rounded-2xl border p-4 text-sm"><p><b>Status:</b> {formatEnum(selected.status)}</p><p className="mt-2"><b>Morning / afternoon / evening:</b> {selected.morning_eggs} / {selected.afternoon_eggs} / {selected.evening_eggs}</p><p className="mt-2"><b>Grades:</b> L {selected.large_eggs}, M {selected.medium_eggs}, S {selected.small_eggs}, damaged {selected.damaged_eggs}, rejected {selected.rejected_eggs}</p>{selected.rejection_reason ? <p className="mt-2 text-destructive"><b>Rejection:</b> {selected.rejection_reason}</p> : null}</div><div className="flex flex-wrap gap-2">{canEdit && selected.status === "DRAFT" ? <Button variant="outline" onClick={() => openEdit(selected)}><Pencil className="size-4" />Edit</Button> : null}{canSubmit && selected.status === "DRAFT" ? <Button onClick={() => void action("submit")}><Send className="size-4" />Submit</Button> : null}{canConfirm && selected.status === "SUBMITTED" ? <Button onClick={() => void action("confirm")}><CheckCircle2 className="size-4" />Confirm</Button> : null}{canConfirm && selected.status === "SUBMITTED" ? <Button variant="destructive" onClick={() => setRejectOpen(true)}><XCircle className="size-4" />Reject</Button> : null}</div></div> : null}</SheetContent></Sheet>
    <Dialog open={rejectOpen} onOpenChange={setRejectOpen}><DialogContent><DialogHeader><DialogTitle>Reject production record</DialogTitle><DialogDescription>Explain what must be corrected before resubmission.</DialogDescription></DialogHeader><Textarea value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} placeholder="Reason for rejection…" /><DialogFooter><Button variant="outline" onClick={() => setRejectOpen(false)}>Cancel</Button><Button variant="destructive" onClick={() => void reject()}>Reject record</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
