"""create farms and farm settings tables

Revision ID: 3182a5039ad3
Revises: 
Create Date: 2026-07-19 16:12:27.119594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3182a5039ad3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Africa/Kampala', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='UGX', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farm_code'), 'farms', ['farm_code'], unique=True)
    op.create_table('farm_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('eggs_per_tray', sa.Integer(), server_default='30', nullable=False),
    sa.Column('low_production_threshold', sa.Numeric(precision=5, scale=2), server_default='70.00', nullable=False),
    sa.Column('mortality_alert_threshold', sa.Numeric(precision=5, scale=2), server_default='1.00', nullable=False),
    sa.Column('vaccination_reminder_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('allow_negative_stock', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_customer_credit', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('maximum_discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('eggs_per_tray > 0', name='ck_farm_settings_eggs_per_tray_positive'),
    sa.CheckConstraint('low_production_threshold >= 0 AND low_production_threshold <= 100', name='ck_farm_settings_low_production_percentage'),
    sa.CheckConstraint('maximum_discount_percentage >= 0 AND maximum_discount_percentage <= 100', name='ck_farm_settings_discount_percentage'),
    sa.CheckConstraint('mortality_alert_threshold >= 0 AND mortality_alert_threshold <= 100', name='ck_farm_settings_mortality_percentage'),
    sa.CheckConstraint('session_timeout_minutes > 0', name='ck_farm_settings_session_timeout_positive'),
    sa.CheckConstraint('vaccination_reminder_days >= 0', name='ck_farm_settings_vaccination_days_nonnegative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_settings_farm_id'), 'farm_settings', ['farm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_settings_farm_id'), table_name='farm_settings')
    op.drop_table('farm_settings')
    op.drop_index(op.f('ix_farms_farm_code'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
