"""create vaccination and poultry health tables

Revision ID: 4717f53185f7
Revises: a6ca92fcc573
Create Date: 2026-07-20 20:54:20.465470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4717f53185f7'
down_revision: Union[str, Sequence[str], None] = 'a6ca92fcc573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_type', sa.String(length=40), server_default='OTHER', nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_egg_withdrawal_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('default_meat_withdrawal_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("product_type IN ('VACCINE', 'ANTIBIOTIC', 'ANTIPARASITIC', 'ANTIFUNGAL', 'VITAMIN', 'MINERAL', 'ELECTROLYTE', 'DISINFECTANT', 'PROBIOTIC', 'OTHER')", name='ck_health_products_valid_type'),
    sa.CheckConstraint('default_egg_withdrawal_days >= 0', name='ck_health_products_egg_withdrawal_nonnegative'),
    sa.CheckConstraint('default_meat_withdrawal_days >= 0', name='ck_health_products_meat_withdrawal_nonnegative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'product_code', name='uq_health_products_farm_code')
    )
    op.create_index(op.f('ix_health_products_farm_id'), 'health_products', ['farm_id'], unique=False)
    op.create_index('ix_health_products_farm_type', 'health_products', ['farm_id', 'product_type'], unique=False)
    op.create_index(op.f('ix_health_products_is_active'), 'health_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_health_products_product_type'), 'health_products', ['product_type'], unique=False)
    op.create_table('health_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('incident_code', sa.String(length=40), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(length=30), server_default='MODERATE', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('affected_birds', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('suspected_cause', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('veterinarian_name', sa.String(length=150), nullable=True),
    sa.Column('isolation_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('isolation_details', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('RESOLVED', 'CLOSED') AND resolution_date IS NOT NULL AND resolved_by IS NOT NULL) OR (status NOT IN ('RESOLVED', 'CLOSED') AND resolution_date IS NULL AND resolved_by IS NULL)", name='ck_health_incidents_resolution_fields'),
    sa.CheckConstraint("severity IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')", name='ck_health_incidents_valid_severity'),
    sa.CheckConstraint("status IN ('OPEN', 'UNDER_TREATMENT', 'MONITORING', 'RESOLVED', 'CLOSED')", name='ck_health_incidents_valid_status'),
    sa.CheckConstraint('affected_birds > 0', name='ck_health_incidents_affected_positive'),
    sa.CheckConstraint('resolution_date IS NULL OR resolution_date >= incident_date', name='ck_health_incidents_resolution_date_valid'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'incident_code', name='uq_health_incidents_farm_code')
    )
    op.create_index('ix_health_incidents_farm_date', 'health_incidents', ['farm_id', 'incident_date'], unique=False)
    op.create_index(op.f('ix_health_incidents_farm_id'), 'health_incidents', ['farm_id'], unique=False)
    op.create_index('ix_health_incidents_farm_severity', 'health_incidents', ['farm_id', 'severity'], unique=False)
    op.create_index('ix_health_incidents_farm_status', 'health_incidents', ['farm_id', 'status'], unique=False)
    op.create_index('ix_health_incidents_flock_date', 'health_incidents', ['flock_id', 'incident_date'], unique=False)
    op.create_index(op.f('ix_health_incidents_flock_id'), 'health_incidents', ['flock_id'], unique=False)
    op.create_index(op.f('ix_health_incidents_incident_date'), 'health_incidents', ['incident_date'], unique=False)
    op.create_index(op.f('ix_health_incidents_recorded_by'), 'health_incidents', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_health_incidents_severity'), 'health_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_health_incidents_status'), 'health_incidents', ['status'], unique=False)
    op.create_table('vaccination_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('vaccine_name', sa.String(length=150), nullable=False),
    sa.Column('disease_target', sa.String(length=200), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('target_age_days', sa.Integer(), nullable=True),
    sa.Column('planned_dose', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=40), server_default='OTHER', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='SCHEDULED', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'CANCELLED' AND cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL) OR (status <> 'CANCELLED' AND cancelled_by IS NULL AND cancelled_at IS NULL AND cancellation_reason IS NULL)", name='ck_vaccination_schedules_cancellation_fields'),
    sa.CheckConstraint("status IN ('SCHEDULED', 'DUE', 'COMPLETED', 'MISSED', 'CANCELLED')", name='ck_vaccination_schedules_valid_status'),
    sa.CheckConstraint('reminder_date IS NULL OR reminder_date <= scheduled_date', name='ck_vaccination_schedules_reminder_before_schedule'),
    sa.CheckConstraint('target_age_days IS NULL OR target_age_days >= 0', name='ck_vaccination_schedules_target_age_nonnegative'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['health_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'flock_id', 'vaccine_name', 'scheduled_date', name='uq_vaccination_schedules_farm_flock_vaccine_date')
    )
    op.create_index(op.f('ix_vaccination_schedules_created_by'), 'vaccination_schedules', ['created_by'], unique=False)
    op.create_index('ix_vaccination_schedules_farm_date', 'vaccination_schedules', ['farm_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_vaccination_schedules_farm_id'), 'vaccination_schedules', ['farm_id'], unique=False)
    op.create_index('ix_vaccination_schedules_farm_status', 'vaccination_schedules', ['farm_id', 'status'], unique=False)
    op.create_index('ix_vaccination_schedules_flock_date', 'vaccination_schedules', ['flock_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_vaccination_schedules_flock_id'), 'vaccination_schedules', ['flock_id'], unique=False)
    op.create_index(op.f('ix_vaccination_schedules_product_id'), 'vaccination_schedules', ['product_id'], unique=False)
    op.create_index(op.f('ix_vaccination_schedules_reminder_date'), 'vaccination_schedules', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_vaccination_schedules_scheduled_date'), 'vaccination_schedules', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_vaccination_schedules_status'), 'vaccination_schedules', ['status'], unique=False)
    op.create_table('treatment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('health_incident_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('birds_treated', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=40), server_default='OTHER', nullable=False),
    sa.Column('purpose', sa.String(length=250), nullable=True),
    sa.Column('prescribed_by', sa.String(length=150), nullable=True),
    sa.Column('treatment_cost', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('egg_withdrawal_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('meat_withdrawal_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('egg_withdrawal_until', sa.Date(), nullable=True),
    sa.Column('meat_withdrawal_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'COMPLETED' AND completed_by IS NOT NULL AND completed_at IS NOT NULL) OR (status <> 'COMPLETED' AND completed_by IS NULL AND completed_at IS NULL)", name='ck_treatment_records_completion_fields'),
    sa.CheckConstraint("status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')", name='ck_treatment_records_valid_status'),
    sa.CheckConstraint('birds_treated > 0', name='ck_treatment_records_birds_positive'),
    sa.CheckConstraint('egg_withdrawal_days >= 0', name='ck_treatment_records_egg_withdrawal_nonnegative'),
    sa.CheckConstraint('egg_withdrawal_until IS NULL OR egg_withdrawal_until >= treatment_date', name='ck_treatment_records_egg_withdrawal_valid'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= treatment_date', name='ck_treatment_records_end_date_valid'),
    sa.CheckConstraint('meat_withdrawal_days >= 0', name='ck_treatment_records_meat_withdrawal_nonnegative'),
    sa.CheckConstraint('meat_withdrawal_until IS NULL OR meat_withdrawal_until >= treatment_date', name='ck_treatment_records_meat_withdrawal_valid'),
    sa.CheckConstraint('treatment_cost >= 0', name='ck_treatment_records_cost_nonnegative'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['health_incident_id'], ['health_incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['health_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_records_egg_withdrawal_until'), 'treatment_records', ['egg_withdrawal_until'], unique=False)
    op.create_index('ix_treatment_records_farm_date', 'treatment_records', ['farm_id', 'treatment_date'], unique=False)
    op.create_index(op.f('ix_treatment_records_farm_id'), 'treatment_records', ['farm_id'], unique=False)
    op.create_index('ix_treatment_records_farm_status', 'treatment_records', ['farm_id', 'status'], unique=False)
    op.create_index('ix_treatment_records_flock_date', 'treatment_records', ['flock_id', 'treatment_date'], unique=False)
    op.create_index(op.f('ix_treatment_records_flock_id'), 'treatment_records', ['flock_id'], unique=False)
    op.create_index(op.f('ix_treatment_records_health_incident_id'), 'treatment_records', ['health_incident_id'], unique=False)
    op.create_index('ix_treatment_records_incident', 'treatment_records', ['health_incident_id'], unique=False)
    op.create_index(op.f('ix_treatment_records_meat_withdrawal_until'), 'treatment_records', ['meat_withdrawal_until'], unique=False)
    op.create_index(op.f('ix_treatment_records_product_id'), 'treatment_records', ['product_id'], unique=False)
    op.create_index(op.f('ix_treatment_records_recorded_by'), 'treatment_records', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_treatment_records_status'), 'treatment_records', ['status'], unique=False)
    op.create_index(op.f('ix_treatment_records_treatment_date'), 'treatment_records', ['treatment_date'], unique=False)
    op.create_table('vaccination_administrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('administration_date', sa.Date(), nullable=False),
    sa.Column('birds_vaccinated', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=40), server_default='OTHER', nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('administered_by_name', sa.String(length=150), nullable=True),
    sa.Column('veterinarian_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('birds_vaccinated > 0', name='ck_vaccination_administrations_birds_positive'),
    sa.CheckConstraint('expiry_date IS NULL OR expiry_date >= administration_date', name='ck_vaccination_administrations_expiry_valid'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['health_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['vaccination_schedules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', name='uq_vaccination_administrations_schedule')
    )
    op.create_index(op.f('ix_vaccination_administrations_administration_date'), 'vaccination_administrations', ['administration_date'], unique=False)
    op.create_index('ix_vaccination_administrations_farm_date', 'vaccination_administrations', ['farm_id', 'administration_date'], unique=False)
    op.create_index(op.f('ix_vaccination_administrations_farm_id'), 'vaccination_administrations', ['farm_id'], unique=False)
    op.create_index('ix_vaccination_administrations_flock_date', 'vaccination_administrations', ['flock_id', 'administration_date'], unique=False)
    op.create_index(op.f('ix_vaccination_administrations_flock_id'), 'vaccination_administrations', ['flock_id'], unique=False)
    op.create_index(op.f('ix_vaccination_administrations_product_id'), 'vaccination_administrations', ['product_id'], unique=False)
    op.create_index(op.f('ix_vaccination_administrations_recorded_by'), 'vaccination_administrations', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_vaccination_administrations_schedule_id'), 'vaccination_administrations', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccination_administrations_schedule_id'), table_name='vaccination_administrations')
    op.drop_index(op.f('ix_vaccination_administrations_recorded_by'), table_name='vaccination_administrations')
    op.drop_index(op.f('ix_vaccination_administrations_product_id'), table_name='vaccination_administrations')
    op.drop_index(op.f('ix_vaccination_administrations_flock_id'), table_name='vaccination_administrations')
    op.drop_index('ix_vaccination_administrations_flock_date', table_name='vaccination_administrations')
    op.drop_index(op.f('ix_vaccination_administrations_farm_id'), table_name='vaccination_administrations')
    op.drop_index('ix_vaccination_administrations_farm_date', table_name='vaccination_administrations')
    op.drop_index(op.f('ix_vaccination_administrations_administration_date'), table_name='vaccination_administrations')
    op.drop_table('vaccination_administrations')
    op.drop_index(op.f('ix_treatment_records_treatment_date'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_status'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_recorded_by'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_product_id'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_meat_withdrawal_until'), table_name='treatment_records')
    op.drop_index('ix_treatment_records_incident', table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_health_incident_id'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_flock_id'), table_name='treatment_records')
    op.drop_index('ix_treatment_records_flock_date', table_name='treatment_records')
    op.drop_index('ix_treatment_records_farm_status', table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_farm_id'), table_name='treatment_records')
    op.drop_index('ix_treatment_records_farm_date', table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_egg_withdrawal_until'), table_name='treatment_records')
    op.drop_table('treatment_records')
    op.drop_index(op.f('ix_vaccination_schedules_status'), table_name='vaccination_schedules')
    op.drop_index(op.f('ix_vaccination_schedules_scheduled_date'), table_name='vaccination_schedules')
    op.drop_index(op.f('ix_vaccination_schedules_reminder_date'), table_name='vaccination_schedules')
    op.drop_index(op.f('ix_vaccination_schedules_product_id'), table_name='vaccination_schedules')
    op.drop_index(op.f('ix_vaccination_schedules_flock_id'), table_name='vaccination_schedules')
    op.drop_index('ix_vaccination_schedules_flock_date', table_name='vaccination_schedules')
    op.drop_index('ix_vaccination_schedules_farm_status', table_name='vaccination_schedules')
    op.drop_index(op.f('ix_vaccination_schedules_farm_id'), table_name='vaccination_schedules')
    op.drop_index('ix_vaccination_schedules_farm_date', table_name='vaccination_schedules')
    op.drop_index(op.f('ix_vaccination_schedules_created_by'), table_name='vaccination_schedules')
    op.drop_table('vaccination_schedules')
    op.drop_index(op.f('ix_health_incidents_status'), table_name='health_incidents')
    op.drop_index(op.f('ix_health_incidents_severity'), table_name='health_incidents')
    op.drop_index(op.f('ix_health_incidents_recorded_by'), table_name='health_incidents')
    op.drop_index(op.f('ix_health_incidents_incident_date'), table_name='health_incidents')
    op.drop_index(op.f('ix_health_incidents_flock_id'), table_name='health_incidents')
    op.drop_index('ix_health_incidents_flock_date', table_name='health_incidents')
    op.drop_index('ix_health_incidents_farm_status', table_name='health_incidents')
    op.drop_index('ix_health_incidents_farm_severity', table_name='health_incidents')
    op.drop_index(op.f('ix_health_incidents_farm_id'), table_name='health_incidents')
    op.drop_index('ix_health_incidents_farm_date', table_name='health_incidents')
    op.drop_table('health_incidents')
    op.drop_index(op.f('ix_health_products_product_type'), table_name='health_products')
    op.drop_index(op.f('ix_health_products_is_active'), table_name='health_products')
    op.drop_index('ix_health_products_farm_type', table_name='health_products')
    op.drop_index(op.f('ix_health_products_farm_id'), table_name='health_products')
    op.drop_table('health_products')
    # ### end Alembic commands ###
