
"""Create the platform identity foundation.

Revision ID: 7b1a6d4f2c90
Revises: 19c4f8a2d6b0
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "7b1a6d4f2c90"
down_revision: str | None = "19c4f8a2d6b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "platform_users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "username",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "password_hash",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "is_super_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "must_change_password",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_platform_users_email",
        "platform_users",
        ["email"],
        unique=True,
    )
    op.create_index(
        "ix_platform_users_username",
        "platform_users",
        ["username"],
        unique=True,
    )

    op.create_table(
        "platform_refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "platform_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "jti",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "replaced_by_jti",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_ip",
            sa.String(length=45),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_platform_refresh_tokens_expires_at",
        "platform_refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_refresh_tokens_jti",
        "platform_refresh_tokens",
        ["jti"],
        unique=True,
    )
    op.create_index(
        "ix_platform_refresh_tokens_platform_user_id",
        "platform_refresh_tokens",
        ["platform_user_id"],
        unique=False,
    )

    op.create_table(
        "platform_audit_logs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "platform_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "target_farm_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "actor_username",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.String(length=20),
            server_default="INFO",
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "resource_type",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "resource_id",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "request_id",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "request_method",
            sa.String(length=12),
            nullable=True,
        ),
        sa.Column(
            "request_path",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "error_code",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_farm_id"],
            ["farms.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_platform_audit_action_occurred",
        "platform_audit_logs",
        ["action", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_actor_occurred",
        "platform_audit_logs",
        ["platform_user_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_action",
        "platform_audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_actor_username",
        "platform_audit_logs",
        ["actor_username"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_occurred_at",
        "platform_audit_logs",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_outcome",
        "platform_audit_logs",
        ["outcome"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_platform_user_id",
        "platform_audit_logs",
        ["platform_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_request_id",
        "platform_audit_logs",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_resource_id",
        "platform_audit_logs",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_resource_type",
        "platform_audit_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_severity",
        "platform_audit_logs",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_target_farm_id",
        "platform_audit_logs",
        ["target_farm_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_target_farm_occurred",
        "platform_audit_logs",
        ["target_farm_id", "occurred_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_platform_audit_target_farm_occurred",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_target_farm_id",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_severity",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_resource_type",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_resource_id",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_request_id",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_platform_user_id",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_outcome",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_occurred_at",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_actor_username",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_logs_action",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_actor_occurred",
        table_name="platform_audit_logs",
    )
    op.drop_index(
        "ix_platform_audit_action_occurred",
        table_name="platform_audit_logs",
    )
    op.drop_table("platform_audit_logs")

    op.drop_index(
        "ix_platform_refresh_tokens_platform_user_id",
        table_name="platform_refresh_tokens",
    )
    op.drop_index(
        "ix_platform_refresh_tokens_jti",
        table_name="platform_refresh_tokens",
    )
    op.drop_index(
        "ix_platform_refresh_tokens_expires_at",
        table_name="platform_refresh_tokens",
    )
    op.drop_table("platform_refresh_tokens")

    op.drop_index(
        "ix_platform_users_username",
        table_name="platform_users",
    )
    op.drop_index(
        "ix_platform_users_email",
        table_name="platform_users",
    )
    op.drop_table("platform_users")
