"""create mortality and culling records

Revision ID: a6ca92fcc573
Revises: e7937705fb5f
Create Date: 2026-07-20 20:11:39.328789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ca92fcc573'
down_revision: Union[str, Sequence[str], None] = 'e7937705fb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bird_loss_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('loss_date', sa.Date(), nullable=False),
    sa.Column('loss_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.String(length=50), server_default='UNKNOWN', nullable=False),
    sa.Column('cause_details', sa.Text(), nullable=True),
    sa.Column('disposal_method', sa.String(length=50), server_default='NOT_RECORDED', nullable=False),
    sa.Column('disposal_details', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('population_before', sa.Integer(), nullable=False),
    sa.Column('population_after', sa.Integer(), nullable=False),
    sa.Column('loss_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('population_transaction_id', sa.UUID(), nullable=False),
    sa.Column('reversal_population_transaction_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'ACTIVE' AND reversal_population_transaction_id IS NULL AND reversed_by IS NULL AND reversed_at IS NULL AND reversal_reason IS NULL) OR (status = 'REVERSED' AND reversal_population_transaction_id IS NOT NULL AND reversed_by IS NOT NULL AND reversed_at IS NOT NULL AND reversal_reason IS NOT NULL)", name='ck_bird_loss_reversal_fields'),
    sa.CheckConstraint("disposal_method IN ('BURIAL', 'INCINERATION', 'COMPOSTING', 'RENDERING', 'VETERINARY_DISPOSAL', 'SOLD_FOR_SLAUGHTER', 'HOME_CONSUMPTION', 'OTHER', 'NOT_RECORDED')", name='ck_bird_loss_valid_disposal'),
    sa.CheckConstraint("loss_type IN ('MORTALITY', 'CULLING')", name='ck_bird_loss_valid_type'),
    sa.CheckConstraint("reason_category IN ('DISEASE', 'INJURY', 'PREDATION', 'HEAT_STRESS', 'COLD_STRESS', 'SUFFOCATION', 'STARVATION', 'DEHYDRATION', 'POISONING', 'LOW_PRODUCTION', 'DEFORMITY', 'OLD_AGE', 'AGGRESSION', 'VETERINARY_RECOMMENDATION', 'UNKNOWN', 'OTHER')", name='ck_bird_loss_valid_reason'),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVERSED')", name='ck_bird_loss_valid_status'),
    sa.CheckConstraint('loss_percentage >= 0 AND loss_percentage <= 100', name='ck_bird_loss_percentage_range'),
    sa.CheckConstraint('population_after = population_before - quantity', name='ck_bird_loss_population_reconciliation'),
    sa.CheckConstraint('population_after >= 0', name='ck_bird_loss_population_after_nonnegative'),
    sa.CheckConstraint('population_before > 0', name='ck_bird_loss_population_before_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_bird_loss_quantity_positive'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['population_transaction_id'], ['flock_population_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_population_transaction_id'], ['flock_population_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_transaction_id', name='uq_bird_loss_population_transaction'),
    sa.UniqueConstraint('reversal_population_transaction_id', name='uq_bird_loss_reversal_population_transaction')
    )
    op.create_index('ix_bird_loss_farm_date', 'bird_loss_records', ['farm_id', 'loss_date'], unique=False)
    op.create_index('ix_bird_loss_farm_status', 'bird_loss_records', ['farm_id', 'status'], unique=False)
    op.create_index('ix_bird_loss_farm_type_date', 'bird_loss_records', ['farm_id', 'loss_type', 'loss_date'], unique=False)
    op.create_index('ix_bird_loss_flock_date', 'bird_loss_records', ['flock_id', 'loss_date'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_farm_id'), 'bird_loss_records', ['farm_id'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_flock_id'), 'bird_loss_records', ['flock_id'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_loss_date'), 'bird_loss_records', ['loss_date'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_loss_type'), 'bird_loss_records', ['loss_type'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_reason_category'), 'bird_loss_records', ['reason_category'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_recorded_by'), 'bird_loss_records', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_bird_loss_records_status'), 'bird_loss_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bird_loss_records_status'), table_name='bird_loss_records')
    op.drop_index(op.f('ix_bird_loss_records_recorded_by'), table_name='bird_loss_records')
    op.drop_index(op.f('ix_bird_loss_records_reason_category'), table_name='bird_loss_records')
    op.drop_index(op.f('ix_bird_loss_records_loss_type'), table_name='bird_loss_records')
    op.drop_index(op.f('ix_bird_loss_records_loss_date'), table_name='bird_loss_records')
    op.drop_index(op.f('ix_bird_loss_records_flock_id'), table_name='bird_loss_records')
    op.drop_index(op.f('ix_bird_loss_records_farm_id'), table_name='bird_loss_records')
    op.drop_index('ix_bird_loss_flock_date', table_name='bird_loss_records')
    op.drop_index('ix_bird_loss_farm_type_date', table_name='bird_loss_records')
    op.drop_index('ix_bird_loss_farm_status', table_name='bird_loss_records')
    op.drop_index('ix_bird_loss_farm_date', table_name='bird_loss_records')
    op.drop_table('bird_loss_records')
    # ### end Alembic commands ###
