"""create persistent alert and notification tables

Revision ID: dbd5bb9e67f8
Revises: fd7c7ced2293
Create Date: 2026-07-21 16:38:49.092005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd5bb9e67f8'
down_revision: Union[str, Sequence[str], None] = 'fd7c7ced2293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_refresh_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_refresh_runs_farm_id'), 'alert_refresh_runs', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alert_refresh_runs_status'), 'alert_refresh_runs', ['status'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('minimum_severity', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'user_id', 'alert_type', 'channel', name='uq_notification_preferences_user_type_channel')
    )
    op.create_index(op.f('ix_notification_preferences_farm_id'), 'notification_preferences', ['farm_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('operational_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=160), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_module', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('action_path', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'fingerprint', name='uq_operational_alerts_farm_fingerprint')
    )
    op.create_index(op.f('ix_operational_alerts_alert_type'), 'operational_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_operational_alerts_assigned_to'), 'operational_alerts', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_operational_alerts_farm_id'), 'operational_alerts', ['farm_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_severity'), 'operational_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_operational_alerts_source_id'), 'operational_alerts', ['source_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_status'), 'operational_alerts', ['status'], unique=False)
    op.create_table('alert_user_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['operational_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'user_id', name='uq_alert_user_states_alert_user')
    )
    op.create_index(op.f('ix_alert_user_states_alert_id'), 'alert_user_states', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_user_states_farm_id'), 'alert_user_states', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alert_user_states_user_id'), 'alert_user_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_user_states_user_id'), table_name='alert_user_states')
    op.drop_index(op.f('ix_alert_user_states_farm_id'), table_name='alert_user_states')
    op.drop_index(op.f('ix_alert_user_states_alert_id'), table_name='alert_user_states')
    op.drop_table('alert_user_states')
    op.drop_index(op.f('ix_operational_alerts_status'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_source_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_severity'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_farm_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_assigned_to'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_alert_type'), table_name='operational_alerts')
    op.drop_table('operational_alerts')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_farm_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_alert_refresh_runs_status'), table_name='alert_refresh_runs')
    op.drop_index(op.f('ix_alert_refresh_runs_farm_id'), table_name='alert_refresh_runs')
    op.drop_table('alert_refresh_runs')
    # ### end Alembic commands ###
