"""create feed management tables

Revision ID: e7937705fb5f
Revises: f75223aeccb8
Create Date: 2026-07-20 18:42:09.029852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7937705fb5f'
down_revision: Union[str, Sequence[str], None] = 'f75223aeccb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('feed_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=40), server_default='OTHER', nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reorder_level_kg', sa.Numeric(precision=14, scale=3), server_default='0.000', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('CHICK_STARTER', 'GROWERS_MASH', 'LAYERS_MASH', 'BROILER_STARTER', 'BROILER_FINISHER', 'CONCENTRATE', 'SUPPLEMENT', 'OTHER')", name='ck_feed_items_valid_category'),
    sa.CheckConstraint('reorder_level_kg >= 0', name='ck_feed_items_reorder_level_nonnegative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'feed_code', name='uq_feed_items_farm_code')
    )
    op.create_index(op.f('ix_feed_items_category'), 'feed_items', ['category'], unique=False)
    op.create_index('ix_feed_items_farm_category', 'feed_items', ['farm_id', 'category'], unique=False)
    op.create_index(op.f('ix_feed_items_farm_id'), 'feed_items', ['farm_id'], unique=False)
    op.create_index(op.f('ix_feed_items_is_active'), 'feed_items', ['is_active'], unique=False)
    op.create_table('feed_inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('transaction_group_id', sa.UUID(), nullable=False),
    sa.Column('feed_item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('signed_quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('reversed_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(transaction_type = 'REVERSAL') OR (transaction_type IN ('PURCHASE_IN', 'RETURN_IN', 'ADJUSTMENT_IN') AND signed_quantity_kg > 0) OR (transaction_type IN ('USAGE_OUT', 'WASTAGE_OUT', 'SUPPLIER_RETURN_OUT', 'ADJUSTMENT_OUT') AND signed_quantity_kg < 0)", name='ck_feed_inventory_sign_matches_type'),
    sa.CheckConstraint("transaction_type IN ('PURCHASE_IN', 'RETURN_IN', 'USAGE_OUT', 'WASTAGE_OUT', 'SUPPLIER_RETURN_OUT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'REVERSAL')", name='ck_feed_inventory_valid_type'),
    sa.CheckConstraint('quantity_kg > 0', name='ck_feed_inventory_quantity_positive'),
    sa.CheckConstraint('signed_quantity_kg <> 0', name='ck_feed_inventory_signed_nonzero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['feed_inventory_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'source_type', 'source_id', 'transaction_type', name='uq_feed_inventory_source_type')
    )
    op.create_index('ix_feed_inventory_farm_item_date', 'feed_inventory_transactions', ['farm_id', 'feed_item_id', 'inventory_date'], unique=False)
    op.create_index('ix_feed_inventory_farm_type_date', 'feed_inventory_transactions', ['farm_id', 'transaction_type', 'inventory_date'], unique=False)
    op.create_index('ix_feed_inventory_source', 'feed_inventory_transactions', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_created_by'), 'feed_inventory_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_farm_id'), 'feed_inventory_transactions', ['farm_id'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_feed_item_id'), 'feed_inventory_transactions', ['feed_item_id'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_inventory_date'), 'feed_inventory_transactions', ['inventory_date'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_reversed_transaction_id'), 'feed_inventory_transactions', ['reversed_transaction_id'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_transaction_group_id'), 'feed_inventory_transactions', ['transaction_group_id'], unique=False)
    op.create_index(op.f('ix_feed_inventory_transactions_transaction_type'), 'feed_inventory_transactions', ['transaction_type'], unique=False)
    op.create_table('feed_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('feed_item_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='RECEIVED', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('RECEIVED', 'VOIDED')", name='ck_feed_purchases_valid_status'),
    sa.CheckConstraint('quantity_kg > 0', name='ck_feed_purchases_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_feed_purchases_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'supplier_id', 'invoice_number', 'feed_item_id', name='uq_feed_purchases_supplier_invoice_item')
    )
    op.create_index(op.f('ix_feed_purchases_created_by'), 'feed_purchases', ['created_by'], unique=False)
    op.create_index('ix_feed_purchases_farm_date', 'feed_purchases', ['farm_id', 'purchase_date'], unique=False)
    op.create_index(op.f('ix_feed_purchases_farm_id'), 'feed_purchases', ['farm_id'], unique=False)
    op.create_index(op.f('ix_feed_purchases_feed_item_id'), 'feed_purchases', ['feed_item_id'], unique=False)
    op.create_index('ix_feed_purchases_item_date', 'feed_purchases', ['feed_item_id', 'purchase_date'], unique=False)
    op.create_index(op.f('ix_feed_purchases_purchase_date'), 'feed_purchases', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_feed_purchases_status'), 'feed_purchases', ['status'], unique=False)
    op.create_index(op.f('ix_feed_purchases_supplier_id'), 'feed_purchases', ['supplier_id'], unique=False)
    op.create_table('feed_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('feed_item_id', sa.UUID(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('feeding_period', sa.String(length=30), server_default='OTHER', nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feeding_period IN ('MORNING', 'AFTERNOON', 'EVENING', 'OTHER')", name='ck_feed_usages_valid_period'),
    sa.CheckConstraint('quantity_kg > 0', name='ck_feed_usages_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_usages_created_by'), 'feed_usages', ['created_by'], unique=False)
    op.create_index('ix_feed_usages_farm_date', 'feed_usages', ['farm_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_feed_usages_farm_id'), 'feed_usages', ['farm_id'], unique=False)
    op.create_index(op.f('ix_feed_usages_feed_item_id'), 'feed_usages', ['feed_item_id'], unique=False)
    op.create_index(op.f('ix_feed_usages_feeding_period'), 'feed_usages', ['feeding_period'], unique=False)
    op.create_index('ix_feed_usages_flock_date', 'feed_usages', ['flock_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_feed_usages_flock_id'), 'feed_usages', ['flock_id'], unique=False)
    op.create_index('ix_feed_usages_item_date', 'feed_usages', ['feed_item_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_feed_usages_usage_date'), 'feed_usages', ['usage_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_usages_usage_date'), table_name='feed_usages')
    op.drop_index('ix_feed_usages_item_date', table_name='feed_usages')
    op.drop_index(op.f('ix_feed_usages_flock_id'), table_name='feed_usages')
    op.drop_index('ix_feed_usages_flock_date', table_name='feed_usages')
    op.drop_index(op.f('ix_feed_usages_feeding_period'), table_name='feed_usages')
    op.drop_index(op.f('ix_feed_usages_feed_item_id'), table_name='feed_usages')
    op.drop_index(op.f('ix_feed_usages_farm_id'), table_name='feed_usages')
    op.drop_index('ix_feed_usages_farm_date', table_name='feed_usages')
    op.drop_index(op.f('ix_feed_usages_created_by'), table_name='feed_usages')
    op.drop_table('feed_usages')
    op.drop_index(op.f('ix_feed_purchases_supplier_id'), table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_status'), table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_purchase_date'), table_name='feed_purchases')
    op.drop_index('ix_feed_purchases_item_date', table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_feed_item_id'), table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_farm_id'), table_name='feed_purchases')
    op.drop_index('ix_feed_purchases_farm_date', table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_created_by'), table_name='feed_purchases')
    op.drop_table('feed_purchases')
    op.drop_index(op.f('ix_feed_inventory_transactions_transaction_type'), table_name='feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_inventory_transactions_transaction_group_id'), table_name='feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_inventory_transactions_reversed_transaction_id'), table_name='feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_inventory_transactions_inventory_date'), table_name='feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_inventory_transactions_feed_item_id'), table_name='feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_inventory_transactions_farm_id'), table_name='feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_inventory_transactions_created_by'), table_name='feed_inventory_transactions')
    op.drop_index('ix_feed_inventory_source', table_name='feed_inventory_transactions')
    op.drop_index('ix_feed_inventory_farm_type_date', table_name='feed_inventory_transactions')
    op.drop_index('ix_feed_inventory_farm_item_date', table_name='feed_inventory_transactions')
    op.drop_table('feed_inventory_transactions')
    op.drop_index(op.f('ix_feed_items_is_active'), table_name='feed_items')
    op.drop_index(op.f('ix_feed_items_farm_id'), table_name='feed_items')
    op.drop_index('ix_feed_items_farm_category', table_name='feed_items')
    op.drop_index(op.f('ix_feed_items_category'), table_name='feed_items')
    op.drop_table('feed_items')
    # ### end Alembic commands ###
