"""create poultry houses table

Revision ID: ed5d2ffe2a21
Revises: f7467e70c39a
Create Date: 2026-07-20 15:54:21.141307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5d2ffe2a21'
down_revision: Union[str, Sequence[str], None] = 'f7467e70c39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry_houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('house_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'UNDER_MAINTENANCE', 'CLOSED')", name='ck_poultry_houses_valid_status'),
    sa.CheckConstraint('capacity > 0', name='ck_poultry_houses_capacity_positive'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'house_code', name='uq_poultry_houses_farm_code')
    )
    op.create_index(op.f('ix_poultry_houses_farm_id'), 'poultry_houses', ['farm_id'], unique=False)
    op.create_index(op.f('ix_poultry_houses_status'), 'poultry_houses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poultry_houses_status'), table_name='poultry_houses')
    op.drop_index(op.f('ix_poultry_houses_farm_id'), table_name='poultry_houses')
    op.drop_table('poultry_houses')
    # ### end Alembic commands ###
