"""create suppliers flocks and population ledger

Revision ID: edfe38d50ac5
Revises: ed5d2ffe2a21
Create Date: 2026-07-20 16:35:09.832230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfe38d50ac5'
down_revision: Union[str, Sequence[str], None] = 'ed5d2ffe2a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('supplier_type', sa.String(length=50), server_default='GENERAL_SUPPLIER', nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("supplier_type IN ('BIRD_SUPPLIER', 'FEED_SUPPLIER', 'MEDICINE_SUPPLIER', 'EQUIPMENT_SUPPLIER', 'GENERAL_SUPPLIER')", name='ck_suppliers_valid_type'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'supplier_code', name='uq_suppliers_farm_code')
    )
    op.create_index(op.f('ix_suppliers_farm_id'), 'suppliers', ['farm_id'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_type'), 'suppliers', ['supplier_type'], unique=False)
    op.create_table('flocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('flock_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('hatch_date', sa.Date(), nullable=True),
    sa.Column('age_at_arrival_days', sa.Integer(), nullable=True),
    sa.Column('initial_population', sa.Integer(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('production_stage', sa.String(length=30), server_default='GROWING', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("production_stage IN ('BROODING', 'GROWING', 'POINT_OF_LAY', 'LAYING', 'MOLTING', 'DEPLETED', 'SOLD')", name='ck_flocks_valid_production_stage'),
    sa.CheckConstraint("status IN ('PLANNED', 'ACTIVE', 'SUSPENDED', 'DEPLETED', 'SOLD', 'ARCHIVED')", name='ck_flocks_valid_status'),
    sa.CheckConstraint('age_at_arrival_days IS NULL OR age_at_arrival_days >= 0', name='ck_flocks_age_at_arrival_nonnegative'),
    sa.CheckConstraint('hatch_date IS NULL OR hatch_date <= arrival_date', name='ck_flocks_hatch_before_arrival'),
    sa.CheckConstraint('initial_population > 0', name='ck_flocks_initial_population_positive'),
    sa.CheckConstraint('purchase_cost >= 0', name='ck_flocks_purchase_cost_nonnegative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['house_id'], ['poultry_houses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'flock_code', name='uq_flocks_farm_code')
    )
    op.create_index('ix_flocks_farm_house_status', 'flocks', ['farm_id', 'house_id', 'status'], unique=False)
    op.create_index(op.f('ix_flocks_farm_id'), 'flocks', ['farm_id'], unique=False)
    op.create_index(op.f('ix_flocks_house_id'), 'flocks', ['house_id'], unique=False)
    op.create_index(op.f('ix_flocks_production_stage'), 'flocks', ['production_stage'], unique=False)
    op.create_index(op.f('ix_flocks_status'), 'flocks', ['status'], unique=False)
    op.create_index(op.f('ix_flocks_supplier_id'), 'flocks', ['supplier_id'], unique=False)
    op.create_table('flock_population_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('signed_quantity', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('reversed_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('INITIAL_PLACEMENT', 'TRANSFER_IN', 'TRANSFER_OUT', 'MORTALITY', 'CULLING', 'BIRD_SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'REVERSAL')", name='ck_flock_population_transactions_valid_type'),
    sa.CheckConstraint('quantity > 0', name='ck_flock_population_transactions_quantity_positive'),
    sa.CheckConstraint('signed_quantity <> 0', name='ck_flock_population_transactions_signed_quantity_nonzero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['flock_population_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flock_population_transactions_created_by'), 'flock_population_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_flock_population_transactions_farm_id'), 'flock_population_transactions', ['farm_id'], unique=False)
    op.create_index('ix_flock_population_transactions_flock_date', 'flock_population_transactions', ['flock_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_flock_population_transactions_flock_id'), 'flock_population_transactions', ['flock_id'], unique=False)
    op.create_index('ix_flock_population_transactions_source', 'flock_population_transactions', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_flock_population_transactions_transaction_date'), 'flock_population_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_flock_population_transactions_transaction_type'), 'flock_population_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flock_population_transactions_transaction_type'), table_name='flock_population_transactions')
    op.drop_index(op.f('ix_flock_population_transactions_transaction_date'), table_name='flock_population_transactions')
    op.drop_index('ix_flock_population_transactions_source', table_name='flock_population_transactions')
    op.drop_index(op.f('ix_flock_population_transactions_flock_id'), table_name='flock_population_transactions')
    op.drop_index('ix_flock_population_transactions_flock_date', table_name='flock_population_transactions')
    op.drop_index(op.f('ix_flock_population_transactions_farm_id'), table_name='flock_population_transactions')
    op.drop_index(op.f('ix_flock_population_transactions_created_by'), table_name='flock_population_transactions')
    op.drop_table('flock_population_transactions')
    op.drop_index(op.f('ix_flocks_supplier_id'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_status'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_production_stage'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_house_id'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_farm_id'), table_name='flocks')
    op.drop_index('ix_flocks_farm_house_status', table_name='flocks')
    op.drop_table('flocks')
    op.drop_index(op.f('ix_suppliers_supplier_type'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_farm_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
