"""create daily egg production table

Revision ID: efbdda021986
Revises: edfe38d50ac5
Create Date: 2026-07-20 17:22:11.031913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbdda021986'
down_revision: Union[str, Sequence[str], None] = 'edfe38d50ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_egg_productions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('birds_present', sa.Integer(), nullable=False),
    sa.Column('morning_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('afternoon_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('evening_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('large_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('medium_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('small_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('damaged_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_eggs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('revision_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('last_updated_by', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'CONFIRMED', 'REJECTED', 'VOIDED')", name='ck_daily_egg_productions_valid_status'),
    sa.CheckConstraint('afternoon_eggs >= 0', name='ck_daily_egg_productions_afternoon_nonnegative'),
    sa.CheckConstraint('birds_present > 0', name='ck_daily_egg_productions_birds_present_positive'),
    sa.CheckConstraint('damaged_eggs >= 0', name='ck_daily_egg_productions_damaged_nonnegative'),
    sa.CheckConstraint('evening_eggs >= 0', name='ck_daily_egg_productions_evening_nonnegative'),
    sa.CheckConstraint('large_eggs >= 0', name='ck_daily_egg_productions_large_nonnegative'),
    sa.CheckConstraint('medium_eggs >= 0', name='ck_daily_egg_productions_medium_nonnegative'),
    sa.CheckConstraint('morning_eggs >= 0', name='ck_daily_egg_productions_morning_nonnegative'),
    sa.CheckConstraint('rejected_eggs >= 0', name='ck_daily_egg_productions_rejected_nonnegative'),
    sa.CheckConstraint('revision_number > 0', name='ck_daily_egg_productions_revision_positive'),
    sa.CheckConstraint('small_eggs >= 0', name='ck_daily_egg_productions_small_nonnegative'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'flock_id', 'production_date', name='uq_daily_egg_productions_farm_flock_date')
    )
    op.create_index('ix_daily_egg_productions_farm_date', 'daily_egg_productions', ['farm_id', 'production_date'], unique=False)
    op.create_index(op.f('ix_daily_egg_productions_farm_id'), 'daily_egg_productions', ['farm_id'], unique=False)
    op.create_index('ix_daily_egg_productions_farm_status', 'daily_egg_productions', ['farm_id', 'status'], unique=False)
    op.create_index('ix_daily_egg_productions_flock_date', 'daily_egg_productions', ['flock_id', 'production_date'], unique=False)
    op.create_index(op.f('ix_daily_egg_productions_flock_id'), 'daily_egg_productions', ['flock_id'], unique=False)
    op.create_index(op.f('ix_daily_egg_productions_production_date'), 'daily_egg_productions', ['production_date'], unique=False)
    op.create_index(op.f('ix_daily_egg_productions_recorded_by'), 'daily_egg_productions', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_daily_egg_productions_status'), 'daily_egg_productions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_egg_productions_status'), table_name='daily_egg_productions')
    op.drop_index(op.f('ix_daily_egg_productions_recorded_by'), table_name='daily_egg_productions')
    op.drop_index(op.f('ix_daily_egg_productions_production_date'), table_name='daily_egg_productions')
    op.drop_index(op.f('ix_daily_egg_productions_flock_id'), table_name='daily_egg_productions')
    op.drop_index('ix_daily_egg_productions_flock_date', table_name='daily_egg_productions')
    op.drop_index('ix_daily_egg_productions_farm_status', table_name='daily_egg_productions')
    op.drop_index(op.f('ix_daily_egg_productions_farm_id'), table_name='daily_egg_productions')
    op.drop_index('ix_daily_egg_productions_farm_date', table_name='daily_egg_productions')
    op.drop_table('daily_egg_productions')
    # ### end Alembic commands ###
