"""create customer sales payment and return tables

Revision ID: f248a3703797
Revises: 4717f53185f7
Create Date: 2026-07-20 23:07:34.838836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f248a3703797'
down_revision: Union[str, Sequence[str], None] = '4717f53185f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_number', sa.String(length=80), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')", name='ck_sales_customers_status'),
    sa.CheckConstraint('credit_limit >= 0', name='ck_sales_customers_credit_limit_nonnegative'),
    sa.CheckConstraint('current_balance >= 0', name='ck_sales_customers_current_balance_nonnegative'),
    sa.CheckConstraint('opening_balance >= 0', name='ck_sales_customers_opening_balance_nonnegative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'customer_code', name='uq_sales_customers_farm_code')
    )
    op.create_index('ix_sales_customers_farm_name', 'sales_customers', ['farm_id', 'name'], unique=False)
    op.create_index('ix_sales_customers_farm_status', 'sales_customers', ['farm_id', 'status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_name_snapshot', sa.String(length=180), nullable=True),
    sa.Column('customer_phone_snapshot', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'CANCELLED') OR (cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)", name='ck_sales_cancellation_audit'),
    sa.CheckConstraint("payment_terms IN ('CASH', 'CREDIT')", name='ck_sales_payment_terms'),
    sa.CheckConstraint("status IN ('DRAFT', 'CONFIRMED', 'PARTIALLY_PAID', 'PAID', 'PARTIALLY_RETURNED', 'RETURNED', 'CANCELLED')", name='ck_sales_status'),
    sa.CheckConstraint('amount_paid <= total_amount', name='ck_sales_amount_paid_not_above_total'),
    sa.CheckConstraint('balance_due = total_amount - amount_paid', name='ck_sales_balance_consistent'),
    sa.CheckConstraint('due_date IS NULL OR due_date >= sale_date', name='ck_sales_due_date'),
    sa.CheckConstraint('subtotal >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0 AND amount_paid >= 0 AND balance_due >= 0', name='ck_sales_amounts_nonnegative'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'invoice_number', name='uq_sales_farm_invoice_number')
    )
    op.create_index('ix_sales_customer_date', 'sales', ['customer_id', 'sale_date'], unique=False)
    op.create_index('ix_sales_farm_date', 'sales', ['farm_id', 'sale_date'], unique=False)
    op.create_index('ix_sales_farm_status', 'sales', ['farm_id', 'status'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('egg_grade', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('eggs_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("unit IN ('PIECE', 'TRAY', 'CRATE')", name='ck_sale_items_unit'),
    sa.CheckConstraint('eggs_per_unit > 0', name='ck_sale_items_eggs_per_unit_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('quantity_returned >= 0 AND quantity_returned <= quantity', name='ck_sale_items_returned_quantity'),
    sa.CheckConstraint('unit_price >= 0 AND line_total >= 0', name='ck_sale_items_amounts_nonnegative'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_sale_grade', 'sale_items', ['sale_id', 'egg_grade'], unique=False)
    op.create_table('sale_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'REVERSED') OR (reversed_by IS NOT NULL AND reversed_at IS NOT NULL AND reversal_reason IS NOT NULL)", name='ck_sale_payments_reversal_audit'),
    sa.CheckConstraint("method IN ('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'OTHER')", name='ck_sale_payments_method'),
    sa.CheckConstraint("status IN ('POSTED', 'REVERSED')", name='ck_sale_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_sale_payments_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'payment_number', name='uq_sale_payments_farm_number')
    )
    op.create_index('ix_sale_payments_customer_date', 'sale_payments', ['customer_id', 'payment_date'], unique=False)
    op.create_index('ix_sale_payments_farm_date', 'sale_payments', ['farm_id', 'payment_date'], unique=False)
    op.create_table('sale_returns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('total_refund', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'REVERSED') OR (reversed_by IS NOT NULL AND reversed_at IS NOT NULL AND reversal_reason IS NOT NULL)", name='ck_sale_returns_reversal_audit'),
    sa.CheckConstraint("status IN ('POSTED', 'REVERSED')", name='ck_sale_returns_status'),
    sa.CheckConstraint('total_refund >= 0', name='ck_sale_returns_refund_nonnegative'),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'return_number', name='uq_sale_returns_farm_number')
    )
    op.create_index('ix_sale_returns_farm_date', 'sale_returns', ['farm_id', 'return_date'], unique=False)
    op.create_index('ix_sale_returns_sale', 'sale_returns', ['sale_id'], unique=False)
    op.create_table('customer_ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('sale_return_id', sa.Uuid(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entry_type IN ('OPENING_BALANCE', 'SALE', 'PAYMENT', 'SALE_RETURN', 'ADJUSTMENT', 'REVERSAL')", name='ck_customer_ledger_entry_type'),
    sa.CheckConstraint('NOT (debit_amount > 0 AND credit_amount > 0)', name='ck_customer_ledger_single_side'),
    sa.CheckConstraint('debit_amount >= 0 AND credit_amount >= 0 AND balance_after >= 0', name='ck_customer_ledger_amounts_nonnegative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['sale_payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_returns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_ledger_customer_date', 'customer_ledger_entries', ['customer_id', 'entry_date'], unique=False)
    op.create_index('ix_customer_ledger_farm_date', 'customer_ledger_entries', ['farm_id', 'entry_date'], unique=False)
    op.create_table('sale_return_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_return_id', sa.Uuid(), nullable=False),
    sa.Column('sale_item_id', sa.Uuid(), nullable=False),
    sa.Column('egg_grade', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("unit IN ('PIECE', 'TRAY', 'CRATE')", name='ck_sale_return_items_unit'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_return_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0 AND line_total >= 0', name='ck_sale_return_items_amounts_nonnegative'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_return_items')
    op.drop_index('ix_customer_ledger_farm_date', table_name='customer_ledger_entries')
    op.drop_index('ix_customer_ledger_customer_date', table_name='customer_ledger_entries')
    op.drop_table('customer_ledger_entries')
    op.drop_index('ix_sale_returns_sale', table_name='sale_returns')
    op.drop_index('ix_sale_returns_farm_date', table_name='sale_returns')
    op.drop_table('sale_returns')
    op.drop_index('ix_sale_payments_farm_date', table_name='sale_payments')
    op.drop_index('ix_sale_payments_customer_date', table_name='sale_payments')
    op.drop_table('sale_payments')
    op.drop_index('ix_sale_items_sale_grade', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_sales_farm_status', table_name='sales')
    op.drop_index('ix_sales_farm_date', table_name='sales')
    op.drop_index('ix_sales_customer_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_sales_customers_farm_status', table_name='sales_customers')
    op.drop_index('ix_sales_customers_farm_name', table_name='sales_customers')
    op.drop_table('sales_customers')
    # ### end Alembic commands ###
