"""create egg inventory transaction ledger

Revision ID: f75223aeccb8
Revises: efbdda021986
Create Date: 2026-07-20 17:56:31.403739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75223aeccb8'
down_revision: Union[str, Sequence[str], None] = 'efbdda021986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egg_inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('transaction_group_id', sa.UUID(), nullable=False),
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('egg_grade', sa.String(length=30), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('signed_quantity', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('reversed_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(transaction_type = 'REVERSAL') OR (transaction_type IN ('PRODUCTION_IN', 'SALE_RETURN_IN', 'ADJUSTMENT_IN') AND signed_quantity > 0) OR (transaction_type IN ('SALE_OUT', 'INTERNAL_USE_OUT', 'DONATION_OUT', 'DAMAGE_OUT', 'ADJUSTMENT_OUT') AND signed_quantity < 0)", name='ck_egg_inventory_sign_matches_type'),
    sa.CheckConstraint("egg_grade IN ('LARGE', 'MEDIUM', 'SMALL', 'DAMAGED', 'REJECTED')", name='ck_egg_inventory_valid_grade'),
    sa.CheckConstraint("transaction_type IN ('PRODUCTION_IN', 'SALE_OUT', 'SALE_RETURN_IN', 'INTERNAL_USE_OUT', 'DONATION_OUT', 'DAMAGE_OUT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'REVERSAL')", name='ck_egg_inventory_valid_type'),
    sa.CheckConstraint('quantity > 0', name='ck_egg_inventory_quantity_positive'),
    sa.CheckConstraint('signed_quantity <> 0', name='ck_egg_inventory_signed_nonzero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['egg_inventory_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'source_type', 'source_id', 'egg_grade', 'transaction_type', name='uq_egg_inventory_source_grade_type')
    )
    op.create_index('ix_egg_inventory_farm_grade_date', 'egg_inventory_transactions', ['farm_id', 'egg_grade', 'inventory_date'], unique=False)
    op.create_index('ix_egg_inventory_farm_type_date', 'egg_inventory_transactions', ['farm_id', 'transaction_type', 'inventory_date'], unique=False)
    op.create_index('ix_egg_inventory_source', 'egg_inventory_transactions', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_created_by'), 'egg_inventory_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_egg_grade'), 'egg_inventory_transactions', ['egg_grade'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_farm_id'), 'egg_inventory_transactions', ['farm_id'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_inventory_date'), 'egg_inventory_transactions', ['inventory_date'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_reversed_transaction_id'), 'egg_inventory_transactions', ['reversed_transaction_id'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_transaction_group_id'), 'egg_inventory_transactions', ['transaction_group_id'], unique=False)
    op.create_index(op.f('ix_egg_inventory_transactions_transaction_type'), 'egg_inventory_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_egg_inventory_transactions_transaction_type'), table_name='egg_inventory_transactions')
    op.drop_index(op.f('ix_egg_inventory_transactions_transaction_group_id'), table_name='egg_inventory_transactions')
    op.drop_index(op.f('ix_egg_inventory_transactions_reversed_transaction_id'), table_name='egg_inventory_transactions')
    op.drop_index(op.f('ix_egg_inventory_transactions_inventory_date'), table_name='egg_inventory_transactions')
    op.drop_index(op.f('ix_egg_inventory_transactions_farm_id'), table_name='egg_inventory_transactions')
    op.drop_index(op.f('ix_egg_inventory_transactions_egg_grade'), table_name='egg_inventory_transactions')
    op.drop_index(op.f('ix_egg_inventory_transactions_created_by'), table_name='egg_inventory_transactions')
    op.drop_index('ix_egg_inventory_source', table_name='egg_inventory_transactions')
    op.drop_index('ix_egg_inventory_farm_type_date', table_name='egg_inventory_transactions')
    op.drop_index('ix_egg_inventory_farm_grade_date', table_name='egg_inventory_transactions')
    op.drop_table('egg_inventory_transactions')
    # ### end Alembic commands ###
