"""create finance expense supplier bill and cash ledger tables

Revision ID: fd7c7ced2293
Revises: f248a3703797
Create Date: 2026-07-20 23:57:23.241279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7c7ced2293'
down_revision: Union[str, Sequence[str], None] = 'f248a3703797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('FEED', 'VETERINARY', 'LABOUR', 'UTILITIES', 'TRANSPORT', 'EQUIPMENT', 'MAINTENANCE', 'HOUSING', 'ADMINISTRATION', 'BIOSECURITY', 'OTHER')", name='ck_finance_expense_categories_kind'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'category_code', name='uq_finance_expense_categories_farm_code')
    )
    op.create_index('ix_finance_expense_categories_farm_active', 'finance_expense_categories', ['farm_id', 'is_active'], unique=False)
    op.create_table('finance_expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('expense_number', sa.String(length=50), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'VOIDED') OR (voided_by IS NOT NULL AND voided_at IS NOT NULL AND void_reason IS NOT NULL)", name='ck_finance_expenses_void_audit'),
    sa.CheckConstraint("payment_method IN ('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'OTHER')", name='ck_finance_expenses_payment_method'),
    sa.CheckConstraint("status IN ('DRAFT', 'POSTED', 'VOIDED')", name='ck_finance_expenses_status'),
    sa.CheckConstraint('amount > 0', name='ck_finance_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['finance_expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'expense_number', name='uq_finance_expenses_farm_number')
    )
    op.create_index('ix_finance_expenses_category_date', 'finance_expenses', ['category_id', 'expense_date'], unique=False)
    op.create_index('ix_finance_expenses_farm_date', 'finance_expenses', ['farm_id', 'expense_date'], unique=False)
    op.create_index('ix_finance_expenses_farm_status', 'finance_expenses', ['farm_id', 'status'], unique=False)
    op.create_table('supplier_bills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('feed_purchase_id', sa.UUID(), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'VOIDED') OR (voided_by IS NOT NULL AND voided_at IS NOT NULL AND void_reason IS NOT NULL)", name='ck_supplier_bills_void_audit'),
    sa.CheckConstraint("status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID', 'VOIDED')", name='ck_supplier_bills_status'),
    sa.CheckConstraint('amount_paid <= total_amount', name='ck_supplier_bills_paid_not_above_total'),
    sa.CheckConstraint('balance_due = total_amount - amount_paid', name='ck_supplier_bills_balance_consistent'),
    sa.CheckConstraint('due_date IS NULL OR due_date >= bill_date', name='ck_supplier_bills_due_date'),
    sa.CheckConstraint('subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0 AND amount_paid >= 0 AND balance_due >= 0', name='ck_supplier_bills_amounts_nonnegative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_purchase_id'], ['feed_purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'bill_number', name='uq_supplier_bills_farm_number'),
    sa.UniqueConstraint('farm_id', 'supplier_id', 'supplier_invoice_number', name='uq_supplier_bills_supplier_invoice')
    )
    op.create_index('ix_supplier_bills_farm_date', 'supplier_bills', ['farm_id', 'bill_date'], unique=False)
    op.create_index('ix_supplier_bills_farm_status', 'supplier_bills', ['farm_id', 'status'], unique=False)
    op.create_index('ix_supplier_bills_supplier_date', 'supplier_bills', ['supplier_id', 'bill_date'], unique=False)
    op.create_table('supplier_bill_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_bill_id', sa.Uuid(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_by', sa.UUID(), nullable=False),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'REVERSED') OR (reversed_by IS NOT NULL AND reversed_at IS NOT NULL AND reversal_reason IS NOT NULL)", name='ck_supplier_bill_payments_reversal_audit'),
    sa.CheckConstraint("method IN ('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'OTHER')", name='ck_supplier_bill_payments_method'),
    sa.CheckConstraint("status IN ('POSTED', 'REVERSED')", name='ck_supplier_bill_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_supplier_bill_payments_amount_positive'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_bill_id'], ['supplier_bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'payment_number', name='uq_supplier_bill_payments_farm_number')
    )
    op.create_index('ix_supplier_bill_payments_farm_date', 'supplier_bill_payments', ['farm_id', 'payment_date'], unique=False)
    op.create_index('ix_supplier_bill_payments_supplier_date', 'supplier_bill_payments', ['supplier_id', 'payment_date'], unique=False)
    op.create_table('cash_ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('expense_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_bill_payment_id', sa.Uuid(), nullable=True),
    sa.Column('sale_payment_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("direction IN ('INFLOW', 'OUTFLOW')", name='ck_cash_ledger_entries_direction'),
    sa.CheckConstraint("entry_type IN ('OPENING_BALANCE', 'SALES_RECEIPT', 'EXPENSE_PAYMENT', 'SUPPLIER_BILL_PAYMENT', 'OTHER_INCOME', 'ADJUSTMENT', 'REVERSAL')", name='ck_cash_ledger_entries_type'),
    sa.CheckConstraint('amount > 0', name='ck_cash_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expense_id'], ['finance_expenses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_payment_id'], ['sale_payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_bill_payment_id'], ['supplier_bill_payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_ledger_entries_farm_date', 'cash_ledger_entries', ['farm_id', 'entry_date'], unique=False)
    op.create_index('ix_cash_ledger_entries_farm_type', 'cash_ledger_entries', ['farm_id', 'entry_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cash_ledger_entries_farm_type', table_name='cash_ledger_entries')
    op.drop_index('ix_cash_ledger_entries_farm_date', table_name='cash_ledger_entries')
    op.drop_table('cash_ledger_entries')
    op.drop_index('ix_supplier_bill_payments_supplier_date', table_name='supplier_bill_payments')
    op.drop_index('ix_supplier_bill_payments_farm_date', table_name='supplier_bill_payments')
    op.drop_table('supplier_bill_payments')
    op.drop_index('ix_supplier_bills_supplier_date', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_farm_status', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_farm_date', table_name='supplier_bills')
    op.drop_table('supplier_bills')
    op.drop_index('ix_finance_expenses_farm_status', table_name='finance_expenses')
    op.drop_index('ix_finance_expenses_farm_date', table_name='finance_expenses')
    op.drop_index('ix_finance_expenses_category_date', table_name='finance_expenses')
    op.drop_table('finance_expenses')
    op.drop_index('ix_finance_expense_categories_farm_active', table_name='finance_expense_categories')
    op.drop_table('finance_expense_categories')
    # ### end Alembic commands ###
