"use client"

import { useEffect, useState } from "react"
import { Bird, Eye, HeartPulse, Plus, RefreshCcw, RotateCcw, Search, ShieldAlert, Skull, XCircle } from "lucide-react"
import { toast } from "sonner"

import { useAuth } from "@/components/auth/auth-provider"
import { EmptyState } from "@/components/operational/empty-state"
import { FormField, NativeSelect, Textarea } from "@/components/operational/form-controls"
import { PageHeading } from "@/components/operational/page-heading"
import { PaginationControls } from "@/components/operational/pagination-controls"
import { StatCard } from "@/components/operational/stat-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { browserApiRequest } from "@/lib/api/browser"
import type { Flock, FlockListResponse } from "@/lib/api/operations"
import type { BirdDisposalMethod, BirdLoss, BirdLossListResponse, BirdLossReason, BirdLossSummary, BirdLossType } from "@/lib/api/stage21c"
import { formatDate, formatEnum, formatNumber, todayIso } from "@/lib/operational/format"

const LIMIT=20
const lossTypes:BirdLossType[]=["MORTALITY","CULLING"]
const reasons:BirdLossReason[]=["DISEASE","INJURY","PREDATION","HEAT_STRESS","COLD_STRESS","SUFFOCATION","STARVATION","DEHYDRATION","POISONING","LOW_PRODUCTION","DEFORMITY","OLD_AGE","AGGRESSION","VETERINARY_RECOMMENDATION","UNKNOWN","OTHER"]
const disposalMethods:BirdDisposalMethod[]=["BURIAL","INCINERATION","COMPOSTING","RENDERING","VETERINARY_DISPOSAL","SOLD_FOR_SLAUGHTER","HOME_CONSUMPTION","OTHER","NOT_RECORDED"]
const emptySummary:BirdLossSummary={date_from:todayIso(),date_to:todayIso(),flock_id:null,active_record_count:0,reversed_record_count:0,mortality_quantity:0,culling_quantity:0,total_loss_quantity:0,average_incident_loss_percentage:"0",maximum_incident_loss_percentage:"0",mortality_threshold_percentage:"0",high_mortality_incidents:0,current_flock_population:null}

export function BirdLossesWorkspace(){
 const {session}=useAuth(); const permissions=session.permissions
 const canRecord=permissions.includes("bird_losses.record"); const canReverse=permissions.includes("bird_losses.reverse")
 const [items,setItems]=useState<BirdLoss[]>([]); const [summary,setSummary]=useState<BirdLossSummary>(emptySummary); const [flocks,setFlocks]=useState<Flock[]>([]); const [total,setTotal]=useState(0); const [offset,setOffset]=useState(0); const [search,setSearch]=useState(""); const [lossType,setLossType]=useState<BirdLossType|"">(""); const [status,setStatus]=useState<"ACTIVE"|"REVERSED"|"">(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [reload,setReload]=useState(0); const [selected,setSelected]=useState<BirdLoss|null>(null); const [createOpen,setCreateOpen]=useState(false); const [saving,setSaving]=useState(false)
 const [form,setForm]=useState({flock_id:"",loss_date:todayIso(),loss_type:"MORTALITY" as BirdLossType,quantity:"1",reason_category:"UNKNOWN" as BirdLossReason,cause_details:"",disposal_method:"NOT_RECORDED" as BirdDisposalMethod,disposal_details:"",location:"",reference:"",notes:""})
 useEffect(()=>{const controller=new AbortController();async function load(){setLoading(true);setError(null);const params=new URLSearchParams({offset:String(offset),limit:String(LIMIT)});if(search.trim())params.set("search",search.trim());if(lossType)params.set("loss_type",lossType);if(status)params.set("status",status);try{const [list,s,f]=await Promise.all([browserApiRequest<BirdLossListResponse>(`/bird-losses?${params}`,{signal:controller.signal}),browserApiRequest<BirdLossSummary>("/bird-losses/summary",{signal:controller.signal}),browserApiRequest<FlockListResponse>("/flocks?limit=100&status=ACTIVE",{signal:controller.signal})]);if(!controller.signal.aborted){setItems(list.items);setTotal(list.total);setSummary(s);setFlocks(f.items)}}catch(c){if(!controller.signal.aborted)setError(c instanceof Error?c.message:"Bird-loss records could not be loaded.")}finally{if(!controller.signal.aborted)setLoading(false)}}void load();return()=>controller.abort()},[offset,search,lossType,status,reload])
 async function create(){if(!form.flock_id||Number(form.quantity)<1)return toast.error("Select a flock and enter a valid quantity.");setSaving(true);try{await browserApiRequest("/bird-losses",{method:"POST",body:JSON.stringify({...form,quantity:Number(form.quantity),cause_details:form.cause_details||null,disposal_details:form.disposal_details||null,location:form.location||null,reference:form.reference||null,notes:form.notes||null})});setCreateOpen(false);setReload(v=>v+1);toast.success(`${formatEnum(form.loss_type)} recorded and flock population updated.`)}catch(c){toast.error(c instanceof Error?c.message:"Bird loss could not be recorded.")}finally{setSaving(false)}}
 async function reverse(item:BirdLoss){const reason=window.prompt("Reason for reversing this record (minimum 5 characters)");if(!reason||reason.trim().length<5)return;try{const saved=await browserApiRequest<BirdLoss>(`/bird-losses/${item.id}/reverse`,{method:"POST",body:JSON.stringify({reversal_date:todayIso(),reason:reason.trim()})});setSelected(saved);setReload(v=>v+1);toast.success("Bird-loss record reversed and population restored.")}catch(c){toast.error(c instanceof Error?c.message:"Record could not be reversed.")}}
 return <div className="space-y-8">
  <PageHeading icon={HeartPulse} eyebrow="Population integrity" title="Bird losses" description="Record mortality and culling with disposal, cause, population impact, thresholds, and audited reversals." actions={<><Button variant="outline" className="rounded-xl" onClick={()=>setReload(v=>v+1)}><RefreshCcw className="size-4"/>Refresh</Button>{canRecord?<Button className="rounded-xl" onClick={()=>setCreateOpen(true)}><Plus className="size-4"/>Record loss</Button>:null}</>}/>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total losses" value={formatNumber(summary.total_loss_quantity)} helper={`${summary.active_record_count} active records`} icon={Skull} tone="danger"/><StatCard label="Mortality" value={formatNumber(summary.mortality_quantity)} helper={`${Number(summary.average_incident_loss_percentage).toFixed(2)}% average incident`} icon={HeartPulse} tone="warning"/><StatCard label="Culling" value={formatNumber(summary.culling_quantity)} helper="Controlled removals" icon={Bird} tone="info"/><StatCard label="High mortality" value={formatNumber(summary.high_mortality_incidents)} helper={`${Number(summary.mortality_threshold_percentage).toFixed(2)}% threshold`} icon={ShieldAlert} tone={summary.high_mortality_incidents?"danger":"primary"}/></div>
  <Card className="overflow-hidden rounded-3xl border-border/75 bg-card/70"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_180px_180px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="h-10 rounded-xl pl-9" placeholder="Search flock, cause, or reference…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></div><NativeSelect className="h-10 rounded-xl" value={lossType} onChange={e=>{setLossType(e.target.value as BirdLossType|"");setOffset(0)}}><option value="">All loss types</option>{lossTypes.map(v=><option key={v}>{v}</option>)}</NativeSelect><NativeSelect className="h-10 rounded-xl" value={status} onChange={e=>{setStatus(e.target.value as "ACTIVE"|"REVERSED"|"");setOffset(0)}}><option value="">All statuses</option><option>ACTIVE</option><option>REVERSED</option></NativeSelect><Button variant="outline" className="rounded-xl" onClick={()=>setReload(v=>v+1)}><RefreshCcw className="size-4"/></Button></div>
   {loading?<div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-16 rounded-xl"/>)}</div>:error?<div className="p-5"><EmptyState icon={XCircle} title="Bird losses unavailable" description={error} actionLabel="Try again" onAction={()=>setReload(v=>v+1)}/></div>:items.length===0?<div className="p-5"><EmptyState icon={Bird} title="No bird losses recorded" description="Record mortality or culling when it occurs; never use manual population adjustments for these events." actionLabel={canRecord?"Record loss":undefined} onAction={canRecord?()=>setCreateOpen(true):undefined}/></div>:<><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Date / flock</TableHead><TableHead>Type</TableHead><TableHead>Quantity</TableHead><TableHead>Cause</TableHead><TableHead>Population</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Open</TableHead></TableRow></TableHeader><TableBody>{items.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{formatDate(item.loss_date)}</p><p className="text-xs text-muted-foreground">{item.flock_code} · {item.house_code}</p></TableCell><TableCell><Badge variant={item.loss_type==="MORTALITY"?"destructive":"outline"}>{formatEnum(item.loss_type)}</Badge></TableCell><TableCell className="font-mono">{formatNumber(item.quantity)}</TableCell><TableCell>{formatEnum(item.reason_category)}</TableCell><TableCell>{formatNumber(item.population_before)} → {formatNumber(item.population_after)}</TableCell><TableCell><Badge variant="outline">{formatEnum(item.status)}</Badge></TableCell><TableCell className="text-right"><Button size="icon-sm" variant="outline" onClick={()=>setSelected(item)}><Eye className="size-4"/></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 p-4 md:hidden">{items.map(item=><button type="button" key={item.id} onClick={()=>setSelected(item)} className="rounded-2xl border p-4 text-left"><div className="flex justify-between"><div><p className="font-medium">{item.flock_name}</p><p className="text-xs text-muted-foreground">{formatDate(item.loss_date)}</p></div><Badge variant="outline">{formatEnum(item.loss_type)}</Badge></div><p className="mt-3 text-sm">{formatNumber(item.quantity)} birds · {formatEnum(item.reason_category)}</p></button>)}</div><PaginationControls offset={offset} limit={LIMIT} total={total} onOffsetChange={setOffset}/></>}
  </Card>
  <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Record mortality or culling</DialogTitle><DialogDescription>This permanently reduces the flock population. Reverse the record only when it was entered incorrectly.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><FormField label="Flock" htmlFor="loss-flock" required><NativeSelect id="loss-flock" value={form.flock_id} onChange={e=>setForm({...form,flock_id:e.target.value})}><option value="">Select flock</option>{flocks.map(f=><option key={f.id} value={f.id}>{f.flock_code} · {f.name} ({formatNumber(f.current_population)})</option>)}</NativeSelect></FormField><FormField label="Loss date" htmlFor="loss-date"><Input id="loss-date" type="date" max={todayIso()} value={form.loss_date} onChange={e=>setForm({...form,loss_date:e.target.value})}/></FormField><FormField label="Loss type" htmlFor="loss-type"><NativeSelect id="loss-type" value={form.loss_type} onChange={e=>setForm({...form,loss_type:e.target.value as BirdLossType})}>{lossTypes.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField label="Quantity" htmlFor="loss-quantity" required><Input id="loss-quantity" type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></FormField><FormField label="Reason category" htmlFor="loss-reason"><NativeSelect id="loss-reason" value={form.reason_category} onChange={e=>setForm({...form,reason_category:e.target.value as BirdLossReason})}>{reasons.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField label="Disposal method" htmlFor="loss-disposal"><NativeSelect id="loss-disposal" value={form.disposal_method} onChange={e=>setForm({...form,disposal_method:e.target.value as BirdDisposalMethod})}>{disposalMethods.map(v=><option key={v}>{v}</option>)}</NativeSelect></FormField><FormField className="sm:col-span-2" label="Cause details" htmlFor="loss-cause"><Textarea id="loss-cause" value={form.cause_details} onChange={e=>setForm({...form,cause_details:e.target.value})}/></FormField><FormField label="Location" htmlFor="loss-location"><Input id="loss-location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></FormField><FormField label="Reference" htmlFor="loss-reference"><Input id="loss-reference" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></FormField><FormField className="sm:col-span-2" label="Notes" htmlFor="loss-notes"><Textarea id="loss-notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></FormField></div><DialogFooter><Button variant="outline" onClick={()=>setCreateOpen(false)}>Cancel</Button><Button disabled={saving} onClick={()=>void create()}>{saving?"Recording…":"Record and update population"}</Button></DialogFooter></DialogContent></Dialog>
  <Sheet open={Boolean(selected)} onOpenChange={open=>!open&&setSelected(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{selected?.flock_name||"Bird-loss record"}</SheetTitle><SheetDescription>{selected?`${formatDate(selected.loss_date)} · ${formatEnum(selected.loss_type)}`:""}</SheetDescription></SheetHeader>{selected?<div className="space-y-5 p-4"><div className="grid grid-cols-2 gap-3"><Card className="p-4"><p className="text-xs text-muted-foreground">Quantity</p><p className="mt-2 font-mono text-2xl font-semibold">{formatNumber(selected.quantity)}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Loss percentage</p><p className="mt-2 font-mono text-2xl font-semibold">{Number(selected.loss_percentage).toFixed(2)}%</p></Card></div><div className="space-y-2 rounded-2xl border p-4 text-sm"><p><b>Reason:</b> {formatEnum(selected.reason_category)}</p><p><b>Disposal:</b> {formatEnum(selected.disposal_method)}</p><p><b>Population:</b> {formatNumber(selected.population_before)} → {formatNumber(selected.population_after)}</p><p><b>Daily mortality:</b> {formatNumber(selected.daily_mortality_quantity)} ({Number(selected.daily_mortality_percentage).toFixed(2)}%)</p>{selected.cause_details?<p><b>Cause details:</b> {selected.cause_details}</p>:null}{selected.reversal_reason?<p><b>Reversal:</b> {selected.reversal_reason}</p>:null}</div>{selected.mortality_alert?<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-500">This incident crossed the farm mortality threshold.</div>:null}{canReverse&&!selected.is_reversed?<Button variant="destructive" onClick={()=>void reverse(selected)}><RotateCcw className="size-4"/>Reverse record</Button>:null}</div>:null}</SheetContent></Sheet>
 </div>
}
