from __future__ import annotations

from importlib import import_module

from app.modules.audit.operations import (
    BeforeLoader,
    OperationAuditSpec,
    audit_operation,
)


OPERATIONAL_AUDIT_SPECS = (
    OperationAuditSpec(
        "app.modules.flocks.service",
        "FlockService",
        "create_flock",
        "flocks",
        "CREATE",
        "Registered a poultry flock.",
        "Flock",
        static_metadata={"linked_effect": "initial flock population placement"},
    ),
    OperationAuditSpec(
        "app.modules.flocks.service",
        "FlockService",
        "update_flock",
        "flocks",
        "UPDATE",
        "Updated a poultry flock.",
        "Flock",
        "flock_id",
        BeforeLoader("get_flock", ("farm_id", "flock_id")),
    ),
    OperationAuditSpec(
        "app.modules.flocks.service",
        "FlockService",
        "create_population_transaction",
        "flocks",
        "CREATE",
        "Recorded a flock population transaction.",
        "FlockPopulationTransaction",
        "flock_id",
        static_metadata={"linked_effect": "flock population balance changed"},
    ),
    OperationAuditSpec(
        "app.modules.production.service",
        "DailyEggProductionService",
        "create_record",
        "production",
        "CREATE",
        "Created a daily egg-production record.",
        "DailyEggProduction",
    ),
    OperationAuditSpec(
        "app.modules.production.service",
        "DailyEggProductionService",
        "update_record",
        "production",
        "UPDATE",
        "Updated a daily egg-production record.",
        "DailyEggProduction",
        "production_id",
        BeforeLoader("get_record", ("farm_id", "production_id")),
    ),
    OperationAuditSpec(
        "app.modules.production.service",
        "DailyEggProductionService",
        "submit_record",
        "production",
        "SUBMIT",
        "Submitted a daily egg-production record.",
        "DailyEggProduction",
        "production_id",
        BeforeLoader("get_record", ("farm_id", "production_id")),
    ),
    OperationAuditSpec(
        "app.modules.production.service",
        "DailyEggProductionService",
        "confirm_record",
        "production",
        "CONFIRM",
        "Confirmed a daily egg-production record.",
        "DailyEggProduction",
        "production_id",
        BeforeLoader("get_record", ("farm_id", "production_id")),
        {"linked_effect": ("confirmed production posted to egg inventory")},
    ),
    OperationAuditSpec(
        "app.modules.production.service",
        "DailyEggProductionService",
        "reject_record",
        "production",
        "REJECT",
        "Rejected a daily egg-production record.",
        "DailyEggProduction",
        "production_id",
        BeforeLoader("get_record", ("farm_id", "production_id")),
    ),
    OperationAuditSpec(
        "app.modules.eggs.service",
        "EggInventoryService",
        "create_adjustment",
        "eggs",
        "CREATE",
        "Created an egg-inventory adjustment.",
        "EggInventoryTransaction",
    ),
    OperationAuditSpec(
        "app.modules.eggs.service",
        "EggInventoryService",
        "create_issue",
        "eggs",
        "CREATE",
        "Issued eggs from inventory.",
        "EggInventoryTransaction",
    ),
    OperationAuditSpec(
        "app.modules.eggs.service",
        "EggInventoryService",
        "reverse_transaction",
        "eggs",
        "REVERSE",
        "Reversed an egg-inventory transaction.",
        "EggInventoryTransaction",
        "transaction_id",
        BeforeLoader(
            "repository.get_transaction",
            ("farm_id", "transaction_id"),
        ),
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "create_item",
        "feed",
        "CREATE",
        "Created a feed item.",
        "FeedItem",
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "update_item",
        "feed",
        "UPDATE",
        "Updated a feed item.",
        "FeedItem",
        "feed_item_id",
        BeforeLoader("get_item", ("farm_id", "feed_item_id")),
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "set_item_active_status",
        "feed",
        "ACTIVE_STATUS",
        "Changed a feed item's active status.",
        "FeedItem",
        "feed_item_id",
        BeforeLoader("get_item", ("farm_id", "feed_item_id")),
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "create_purchase",
        "feed",
        "CREATE",
        "Recorded a feed purchase.",
        "FeedPurchase",
        static_metadata={"linked_effect": "feed inventory balance increased"},
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "void_purchase",
        "feed",
        "VOID",
        "Voided a feed purchase.",
        "FeedPurchase",
        "purchase_id",
        BeforeLoader("get_purchase", ("farm_id", "purchase_id")),
        {"linked_effect": ("feed purchase inventory posting reversed")},
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "create_usage",
        "feed",
        "CREATE",
        "Recorded flock feed usage.",
        "FeedUsage",
        static_metadata={"linked_effect": "feed inventory balance decreased"},
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "create_adjustment",
        "feed",
        "CREATE",
        "Created a feed-inventory adjustment.",
        "FeedInventoryTransaction",
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "create_wastage",
        "feed",
        "CREATE",
        "Recorded feed wastage.",
        "FeedInventoryTransaction",
        static_metadata={"linked_effect": "feed inventory balance decreased"},
    ),
    OperationAuditSpec(
        "app.modules.feed.service",
        "FeedService",
        "reverse_transaction",
        "feed",
        "REVERSE",
        "Reversed a feed-inventory transaction.",
        "FeedInventoryTransaction",
        "transaction_id",
        BeforeLoader(
            "repository.get_inventory_transaction",
            ("farm_id", "transaction_id"),
        ),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "create_product",
        "health",
        "CREATE",
        "Created a veterinary health product.",
        "HealthProduct",
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "update_product",
        "health",
        "UPDATE",
        "Updated a veterinary health product.",
        "HealthProduct",
        "product_id",
        BeforeLoader("get_product", ("farm_id", "product_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "set_product_active_status",
        "health",
        "ACTIVE_STATUS",
        "Changed a health product's active status.",
        "HealthProduct",
        "product_id",
        BeforeLoader("get_product", ("farm_id", "product_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "create_schedule",
        "health",
        "CREATE",
        "Created a vaccination schedule.",
        "VaccinationSchedule",
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "update_schedule",
        "health",
        "UPDATE",
        "Updated a vaccination schedule.",
        "VaccinationSchedule",
        "schedule_id",
        BeforeLoader("get_schedule", ("farm_id", "schedule_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "complete_schedule",
        "health",
        "COMPLETE",
        "Completed a vaccination schedule.",
        "VaccinationSchedule",
        "schedule_id",
        BeforeLoader("get_schedule", ("farm_id", "schedule_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "cancel_schedule",
        "health",
        "CANCEL",
        "Cancelled a vaccination schedule.",
        "VaccinationSchedule",
        "schedule_id",
        BeforeLoader("get_schedule", ("farm_id", "schedule_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "create_incident",
        "health",
        "CREATE",
        "Created a flock health incident.",
        "HealthIncident",
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "update_incident",
        "health",
        "UPDATE",
        "Updated a flock health incident.",
        "HealthIncident",
        "incident_id",
        BeforeLoader("get_incident", ("farm_id", "incident_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "resolve_incident",
        "health",
        "RESOLVE",
        "Resolved a flock health incident.",
        "HealthIncident",
        "incident_id",
        BeforeLoader("get_incident", ("farm_id", "incident_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "create_treatment",
        "health",
        "CREATE",
        "Created a flock treatment record.",
        "TreatmentRecord",
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "complete_treatment",
        "health",
        "COMPLETE",
        "Completed a flock treatment record.",
        "TreatmentRecord",
        "treatment_id",
        BeforeLoader("get_treatment", ("farm_id", "treatment_id")),
    ),
    OperationAuditSpec(
        "app.modules.health.service",
        "HealthService",
        "cancel_treatment",
        "health",
        "CANCEL",
        "Cancelled a flock treatment record.",
        "TreatmentRecord",
        "treatment_id",
        BeforeLoader("get_treatment", ("farm_id", "treatment_id")),
    ),
    OperationAuditSpec(
        "app.modules.bird_losses.service",
        "BirdLossService",
        "create_record",
        "bird_losses",
        "CREATE",
        "Recorded a mortality or culling event.",
        "BirdLossRecord",
        static_metadata={"linked_effect": "flock population balance decreased"},
    ),
    OperationAuditSpec(
        "app.modules.bird_losses.service",
        "BirdLossService",
        "reverse_record",
        "bird_losses",
        "REVERSE",
        "Reversed a mortality or culling record.",
        "BirdLossRecord",
        "record_id",
        BeforeLoader("get_record", ("farm_id", "record_id")),
        {"linked_effect": "flock population balance restored"},
    ),
)


_INSTALLED = False


def install_operational_auditing() -> int:
    global _INSTALLED

    if _INSTALLED:
        return 0

    installed = 0

    for spec in OPERATIONAL_AUDIT_SPECS:
        module = import_module(spec.module_path)
        service_class = getattr(
            module,
            spec.class_name,
        )
        operation = getattr(
            service_class,
            spec.method_name,
        )

        if getattr(
            operation,
            "__poultrypulse_audit_wrapped__",
            False,
        ):
            continue

        setattr(
            service_class,
            spec.method_name,
            audit_operation(spec)(operation),
        )
        installed += 1

    _INSTALLED = True
    return installed
