"use client"
import { useEffect, useMemo, useState } from "react"
import { Boxes, Egg, PackageMinus, Plus, RefreshCcw, RotateCcw, Search, ShoppingBasket } from "lucide-react"
import { toast } from "sonner"
import { useAuth } from "@/components/auth/auth-provider"
import { EmptyState } from "@/components/operational/empty-state"
import { FormField, NativeSelect, Textarea } from "@/components/operational/form-controls"
import { PageHeading } from "@/components/operational/page-heading"
import { PaginationControls } from "@/components/operational/pagination-controls"
import { StatCard } from "@/components/operational/stat-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { browserApiRequest } from "@/lib/api/browser"
import type { EggGrade, EggSummary, EggTransaction, EggTransactionListResponse, EggTransactionType } from "@/lib/api/stage21b"
import { formatDate, formatEnum, formatNumber, todayIso } from "@/lib/operational/format"
const LIMIT=20; const grades: EggGrade[]=["LARGE","MEDIUM","SMALL","DAMAGED","REJECTED"]
type Mode="adjustment"|"issue"|"reverse"
export function EggInventoryWorkspace({ initiallyAdjust=false }: { initiallyAdjust?: boolean }) {
 const {session}=useAuth(); const [summary,setSummary]=useState<EggSummary|null>(null); const [items,setItems]=useState<EggTransaction[]>([]); const [total,setTotal]=useState(0); const [offset,setOffset]=useState(0); const [grade,setGrade]=useState<EggGrade|"">(""); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [reload,setReload]=useState(0); const [dialog,setDialog]=useState<Mode|null>(initiallyAdjust?"adjustment":null); const [target,setTarget]=useState<EggTransaction|null>(null); const [form,setForm]=useState({inventory_date:todayIso(),egg_grade:"LARGE" as EggGrade,transaction_type:"ADJUSTMENT_IN" as EggTransactionType,quantity:"",reference:"",description:""}); const [saving,setSaving]=useState(false)
 const canAdjust=session.permissions.includes("eggs.adjust"), canIssue=session.permissions.includes("eggs.issue"), canReverse=session.permissions.includes("eggs.reverse")
 const query=useMemo(()=>{const p=new URLSearchParams({offset:String(offset),limit:String(LIMIT)});if(grade)p.set("egg_grade",grade);if(search.trim())p.set("source_type",search.trim());return p.toString()},[grade,offset,search])
 useEffect(()=>{const c=new AbortController();async function load(){setLoading(true);try{const [s,l]=await Promise.all([browserApiRequest<EggSummary>("/egg-inventory/balances",{signal:c.signal}),browserApiRequest<EggTransactionListResponse>(`/egg-inventory/transactions?${query}`,{signal:c.signal})]);if(!c.signal.aborted){setSummary(s);setItems(l.items);setTotal(l.total);setError(null)}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:"Egg inventory could not be loaded.")}finally{if(!c.signal.aborted)setLoading(false)}}void load();return()=>c.abort()},[query,reload])
 function open(mode:Mode,item?:EggTransaction){setTarget(item??null);setDialog(mode);setForm({inventory_date:todayIso(),egg_grade:item?.egg_grade??"LARGE",transaction_type:mode==="issue"?"INTERNAL_USE_OUT":mode==="reverse"?"REVERSAL":"ADJUSTMENT_IN",quantity:"",reference:"",description:""})}
 async function save(){if(dialog==="reverse"&&!target)return;if(form.description.trim().length<5)return toast.error("Description or reason must be at least 5 characters.");setSaving(true);try{if(dialog==="reverse"){await browserApiRequest(`/egg-inventory/transactions/${target!.id}/reverse`,{method:"POST",body:JSON.stringify({inventory_date:form.inventory_date,reason:form.description.trim()})})}else{await browserApiRequest(dialog==="issue"?"/egg-inventory/issues":"/egg-inventory/adjustments",{method:"POST",body:JSON.stringify({inventory_date:form.inventory_date,egg_grade:form.egg_grade,transaction_type:form.transaction_type,quantity:Number(form.quantity),reference:form.reference||null,description:form.description.trim()})})}toast.success(dialog==="reverse"?"Transaction reversed.":dialog==="issue"?"Eggs issued.":"Inventory adjusted.");setDialog(null);setReload(v=>v+1)}catch(e){toast.error(e instanceof Error?e.message:"Inventory action failed.")}finally{setSaving(false)}}
 return <div className="space-y-8"><PageHeading icon={Boxes} eyebrow="Farm operations" title="Egg inventory" description="Monitor grade balances, trays, loose eggs, and every stock movement." actions={<>{canIssue?<Button variant="outline" className="rounded-xl" onClick={()=>open("issue")}><PackageMinus className="size-4"/>Issue eggs</Button>:null}{canAdjust?<Button className="rounded-xl" onClick={()=>open("adjustment")}><Plus className="size-4"/>Adjust stock</Button>:null}</>} />
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="All eggs" value={formatNumber(summary?.total_all_eggs??0)} helper="All grades in stock" icon={Egg}/><StatCard label="Saleable eggs" value={formatNumber(summary?.total_saleable_eggs??0)} helper={`${formatNumber(summary?.total_saleable_trays??0)} full trays`} icon={ShoppingBasket} tone="info"/><StatCard label="Loose saleable" value={formatNumber(summary?.total_saleable_loose_eggs??0)} helper={`${summary?.eggs_per_tray??30} eggs per tray`} icon={Boxes}/><StatCard label="Non-saleable" value={formatNumber(summary?.total_non_saleable_eggs??0)} helper="Damaged and rejected" icon={PackageMinus} tone="warning"/></div>
 {summary?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{summary.balances.map(b=><Card key={b.egg_grade} className="rounded-2xl p-4"><div className="flex justify-between"><p className="text-sm font-medium">{formatEnum(b.egg_grade)}</p><Badge variant="outline">{b.is_saleable?"Saleable":"Non-saleable"}</Badge></div><p className="mt-4 font-mono text-2xl font-semibold">{formatNumber(b.balance_eggs)}</p><p className="mt-1 text-xs text-muted-foreground">{b.trays} trays · {b.loose_eggs} loose</p></Card>)}</div>:null}
 <Card className="overflow-hidden rounded-3xl"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_220px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="h-10 rounded-xl pl-9" placeholder="Filter by source type…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></div><NativeSelect value={grade} onChange={e=>{setGrade(e.target.value as EggGrade|"");setOffset(0)}}><option value="">All grades</option>{grades.map(g=><option key={g} value={g}>{formatEnum(g)}</option>)}</NativeSelect><Button variant="outline" onClick={()=>setReload(v=>v+1)}><RefreshCcw className="size-4"/>Refresh</Button></div>{loading?<div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-16"/>)}</div>:error?<div className="p-5"><EmptyState icon={Boxes} title="Inventory unavailable" description={error}/></div>:items.length===0?<div className="p-5"><EmptyState icon={Egg} title="No inventory transactions" description="Confirmed production and manual stock actions will appear here."/></div>:<><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead className="pl-5">Date</TableHead><TableHead>Grade</TableHead><TableHead>Movement</TableHead><TableHead>Source</TableHead><TableHead className="text-right">Quantity</TableHead><TableHead className="pr-5 text-right">Action</TableHead></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell className="pl-5">{formatDate(i.inventory_date)}</TableCell><TableCell>{formatEnum(i.egg_grade)}</TableCell><TableCell><Badge variant="outline">{formatEnum(i.transaction_type)}</Badge></TableCell><TableCell>{formatEnum(i.source_type)}</TableCell><TableCell className={`text-right font-mono ${i.signed_quantity<0?"text-destructive":"text-primary"}`}>{i.signed_quantity>0?"+":""}{formatNumber(i.signed_quantity)}</TableCell><TableCell className="pr-5 text-right">{canReverse&&!i.is_reversal&&!i.reversed_transaction_id?<Button size="icon-sm" variant="outline" onClick={()=>open("reverse",i)}><RotateCcw className="size-4"/></Button>:null}</TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 p-4 md:hidden">{items.map(i=><div key={i.id} className="rounded-2xl border p-4"><div className="flex justify-between"><div><p className="font-medium">{formatEnum(i.egg_grade)}</p><p className="text-xs text-muted-foreground">{formatDate(i.inventory_date)}</p></div><p className="font-mono">{i.signed_quantity>0?"+":""}{i.signed_quantity}</p></div><p className="mt-2 text-xs text-muted-foreground">{formatEnum(i.transaction_type)} · {formatEnum(i.source_type)}</p></div>)}</div><PaginationControls offset={offset} limit={LIMIT} total={total} onOffsetChange={setOffset}/></>}</Card>
 <Dialog open={Boolean(dialog)} onOpenChange={o=>!o&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog==="reverse"?"Reverse transaction":dialog==="issue"?"Issue eggs":"Adjust egg inventory"}</DialogTitle><DialogDescription>{dialog==="reverse"?"The reversal creates an auditable counter-transaction.":"Record a controlled manual stock movement."}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><FormField label="Date" htmlFor="egg-date"><Input id="egg-date" type="date" value={form.inventory_date} onChange={e=>setForm({...form,inventory_date:e.target.value})}/></FormField>{dialog!=="reverse"?<><FormField label="Grade" htmlFor="egg-grade"><NativeSelect id="egg-grade" value={form.egg_grade} onChange={e=>setForm({...form,egg_grade:e.target.value as EggGrade})}>{grades.map(g=><option key={g} value={g}>{formatEnum(g)}</option>)}</NativeSelect></FormField><FormField label="Movement" htmlFor="egg-type"><NativeSelect id="egg-type" value={form.transaction_type} onChange={e=>setForm({...form,transaction_type:e.target.value as EggTransactionType})}>{dialog==="issue"?<><option value="INTERNAL_USE_OUT">Internal use</option><option value="DONATION_OUT">Donation</option><option value="DAMAGE_OUT">Damage</option></>:<><option value="ADJUSTMENT_IN">Adjustment in</option><option value="ADJUSTMENT_OUT">Adjustment out</option></>}</NativeSelect></FormField><FormField label="Quantity" htmlFor="egg-qty"><Input id="egg-qty" type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></FormField><FormField label="Reference" htmlFor="egg-ref"><Input id="egg-ref" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></FormField></>:null}<FormField className="sm:col-span-2" label={dialog==="reverse"?"Reversal reason":"Description"} htmlFor="egg-desc" required><Textarea id="egg-desc" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></FormField></div><DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>Cancel</Button><Button disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save"}</Button></DialogFooter></DialogContent></Dialog></div>
}
